cyberdrop_dl/scraper/crawlers/simpcity_crawler.py

Changed simpcity `post_data_attribute` from `data-time` to `data-timestamp`.

Fix simpcity scraper

---

.github/workflows/publish-to-pypi.yaml
pyproject.toml

Update publish to pypi workflow

Update publish action

---

cyberdrop_dl/__init__.py
pyproject.toml

this uses 
https://stackoverflow.com/questions/74795811/get-version-of-python-poetry-project-from-inside-the-project
to parse metadata for cyberdrop-dl-patched own version number

Version patch

---

cyberdrop_dl/__init__.py

https://discuss.python.org/t/module-importlib-has-no-attribute-metadata/20947
fix weird  error with importlib subpackage

import importlib.metadata

---

pyproject.toml

modify poetry

---

cyberdrop_dl/scraper/crawlers/rule34vault_crawler.py
pyproject.toml

Force highest quality downloads from rule34vault by removing the thumbnail and small tags from URLs.

Update rule34vault download quality

---

cyberdrop_dl/scraper/crawlers/rule34vault_crawler.py
pyproject.toml

Fixed rule34vault tag search scraping.

Update rule34vault tag scraping

---

.gitignore
cyberdrop_dl/scraper/crawlers/rule34vault_crawler.py
pyproject.toml

Fixed undesired files being downloaded from rule34vault & also increased download quality for some videos.

Patch undesired rule34vault video downloads

---

cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/utils/dataclasses/url_objects.py
pyproject.toml

Fix issue with .created_at and .completed_at not be attributes

add created_at and completed_at to init

---

cyberdrop_dl/scraper/scraper.py
docs/reference/configuration-options/global-settings.md
pyproject.toml

sorry this fixes the text line I added

add download rate limit

---

cyberdrop_dl/clients/download_client.py
pyproject.toml

This uses the resp.headers for checking bunkr
instead of the newly created download headers for the final download process
I also changed the var name to make it clear which is which
since they are both used in that function

Jdownloader

---

cyberdrop_dl/managers/args_manager.py
cyberdrop_dl/utils/args/args.py
cyberdrop_dl/utils/args/config_definitions.py
cyberdrop_dl/utils/database/tables/history_table.py
cyberdrop_dl/utils/sorting.py
docs/reference/cli-arguments.md
docs/reference/configuration-options/settings.md
pyproject.toml

Added a config option and command line argument to only sort files that were downloaded by CDL.

 Add option to only sort files downloaded by CDL

---

cyberdrop_dl/ui/prompts/general_prompts.py
cyberdrop_dl/ui/ui.py
cyberdrop_dl/utils/changelog.py
pyproject.toml

Implement a changelog in the main UI using pydoc. The method for writing to the changelog is a little scuffed but I just quickly threw it together. Gets the job done and doesn't look too bad.

Implement Changelog

---

cyberdrop_dl/managers/args_manager.py
cyberdrop_dl/utils/args/args.py
cyberdrop_dl/utils/changelog.py
cyberdrop_dl/utils/sorting.py
pyproject.toml

Fix sorting logic & sorting CLI argument.

Fix sorting logic

---

cyberdrop_dl/managers/progress_manager.py
cyberdrop_dl/ui/progress/downloads_progress.py
cyberdrop_dl/ui/progress/file_progress.py
cyberdrop_dl/ui/progress/sort_progress.py
cyberdrop_dl/utils/changelog.py
cyberdrop_dl/utils/sorting.py
docs/reference/configuration-options/settings.md
pyproject.toml

Updated the sorting progress bar to be more like that of downloading files, indicating how many files are being sorted, how many are in the queue, and the progress of each folder.

Update sorting progress bar

---

cyberdrop_dl/scraper/crawlers/gofile_crawler.py
cyberdrop_dl/utils/changelog.py
pyproject.toml

Add the ability to detect private gofile folders and raise an error when one is detected.

Detect private gofile folders

---

cyberdrop_dl/managers/config_manager.py
cyberdrop_dl/utils/changelog.py
docs/reference/configuration-options/authentication.md
pyproject.toml

Added local authentication settings. If an `authentication.yaml` file is placed within a config directory, that config will use those instead of the global authentication settings.

Local authentication configs

---

cyberdrop_dl/managers/cache_manager.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/scraper/crawlers/simpcity_crawler.py

Reverts jbsparrow/CyberDropDownloader#122

Revert "add simpcity cache to reduce load"

---

cyberdrop_dl/utils/utilities.py
docs/reference/configuration-options/settings.md
pyproject.toml

This PR adds support to rename multipart archive files created by 2 of the most popular compression programs: Winrar and 7zip/7z. 
Both use a 2 extension identifier for multipart archives:
- Winrar uses the first extension for the part index and the second extension for the format. 
- 7zip/7z uses the first extension for the format and the second extension for the part index
Both require the `base_name` of all the parts to be the same. If all the parts do not follow the previous conditions, the extraction fails (Winrar) or exits immediately (7zip)
Renaming will only be done when CDL runs with` --remove-generated-id-from-filenames`.
Tested with a 100MB binary file of random data compressed as 2 files of 50MB for each supported format. All the parts where uploaded to bunkr ([album …

Feature: rename multipart archives files with --remove-generated-id-from-filenames

---

.gitignore

Add CDL debug file to .gitignore

---

cyberdrop_dl/downloader/downloader.py

Replace raw trace-back logs with rich trace-backs. Missed a few from PR #131

refactor: replace raw traceback logs with rich tracebacks

---

CHANGELOG.md
cyberdrop_dl/managers/manager.py
cyberdrop_dl/utils/args/args.py
docs/reference/cli-arguments.md
pyproject.toml

Update Toggleable CLI Arguments to not override their config file counterparts

Implement Toggleable CLI Arguments

---

cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
pyproject.toml

This checking of the last  page for simpcity
currently it only works on the first check, and for subsequent checks the last_page query always return True

Caching fix last page

---

cyberdrop_dl/managers/cache_manager.py

We can use get to access the keys instead of looping through each one

use get to access key

---

CHANGELOG.md
cyberdrop_dl/clients/errors.py
cyberdrop_dl/main.py
cyberdrop_dl/managers/config_manager.py
pyproject.toml

Related to #161 
Would prevent the error from happening again but requires intervention by the user to fix the config_file if they were affected.

fix: scan_folder saved as path to config_file

---

cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py

- update base domain
- update crawler's logic and css selectors to work on the new site design
fixes #176

fix: update bunkr crawler

---

cyberdrop_dl/managers/log_manager.py
cyberdrop_dl/scraper/scraper.py

Fixes  issue where files deleted  by purge_tree error as non existing

fixes for empty files being purged

---

cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
cyberdrop_dl/scraper/scraper.py

1. Add support for videos, photos, albums, playlist, profiles and search results of tokyomotion.net

feat: add support for Tokyomotion URLs 

---

cyberdrop_dl/clients/hash_client.py

simplify hash conditon

---

cyberdrop_dl/scraper/crawlers/imgbox_crawler.py

imgbox may return `200` even if the album was not found

fix: handle deleted imgbox albums

---

cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/main.py
cyberdrop_dl/managers/live_manager.py
cyberdrop_dl/utils/utilities.py

same changes as #131 but applied to master branch for next mayor release

feat: rich logger

---

cyberdrop_dl/managers/progress_manager.py
cyberdrop_dl/ui/progress/downloads_progress.py
cyberdrop_dl/ui/progress/file_progress.py
cyberdrop_dl/ui/progress/hash_progress.py
cyberdrop_dl/ui/progress/sort_progress.py
cyberdrop_dl/ui/progress/statistic_progress.py

- remove redundant 'X of Y files' from every progress bar 
- sort scrape and download errors by reverse frequency 
- use equal height for top row UI
- fix padding issues

refactor: simplify UI for v5.7

---

CHANGELOG.md
docs/reference/configuration-options/settings.md
pyproject.toml

> [!IMPORTANT]  
> This should be the last merge before next release. Any other currently open PRs (latest #193) must be merged, tested to make sure everything is working fine, and then merge this PR
This PR also restrict python version to 3.12. Some dependencies do not support 3.13 yet and some users are complaining with build error during PIP install.

docs: changelog and wiki updates for v5.7

---

cyberdrop_dl/utils/utilities.py

fix: bunkr file extension parsing

---

CHANGELOG.md
pyproject.toml

Include real-debrid support in changelog

Update changelog for real-debrid.

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/scraper/crawlers/cyberdrop_crawler.py
cyberdrop_dl/scraper/scraper.py

1. add support for % encoded URLs in input file
2. add support for cyberdrop direct links (`https://cyberdrop.me/<filename>`). These are often % encoded cause they may have spaces
3. Better error handling (cyberdrop)

feat: add support for % encoded URLs in input file

---

cyberdrop_dl/clients/download_client.py

fix: only_host download filter

---

.github/workflows/create_release.yaml
scripts/release/start_linux.sh
scripts/release/start_macOS.command
scripts/release/start_windows.bat

1. Add release start files to the repo to track changes if any
2. Add a manually triggered gh-action to create a new release with a zip of the current start scripts and the current tag

cd: add release start scripts to repo

---

.github/workflows/codeql-analysis.yml

v2 is deprecated and will be removed on dec 2024

ci: upgrade CodeQL action to v3

---

cyberdrop_dl/scraper/crawlers/coomer_crawler.py
cyberdrop_dl/scraper/crawlers/kemono_crawler.py

Fixes error mentioned on https://github.com/jbsparrow/CyberDropDownloader/issues/234#issuecomment-2461309340

fix: prepare files before looping through them (coomer/kemono)

---

cyberdrop_dl/managers/log_manager.py

1. Use a file lock to serialize writing
2. Remove additional newline
3. Use quotes for all values
Fixes #251

fix: csv logger

---

cyberdrop_dl/main.py
cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/utils/dataclasses/url_objects.py
pyproject.toml

Possible error by ruff putting `from pathlib import Path` in `TYPE_CHECKING`?

Fix scraping bug

---

.gitignore

Add `/Old Files/` to `.gitignore`.

Ignore Old Files Directory

---

cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
cyberdrop_dl/scraper/crawlers/xbunker_crawler.py
cyberdrop_dl/utils/args/browser_cookie_extraction.py

There is an issue with a unneeded async call
when using the get_forum_post function
There is also an issue with saving and reading cookies from sites like socialmediagirls
social media girls had an out of index error as well

fix crawlers

---

cyberdrop_dl/managers/config_manager.py
cyberdrop_dl/ui/prompts/settings_user_prompts.py
cyberdrop_dl/utils/args/browser_cookie_extraction.py
cyberdrop_dl/utils/args/config_definitions.py
docs/reference/configuration-options/settings.md

- add prompts for cookie extraction options
- also fixes issue where config validation fails, because global_settings_data was not set

Cookie Extraction Prompt menu

---

cyberdrop_dl/main.py
cyberdrop_dl/managers/client_manager.py
cyberdrop_dl/managers/config_manager.py
cyberdrop_dl/managers/real_debrid/api.py
cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
cyberdrop_dl/ui/prompts/settings_hash_prompts.py
cyberdrop_dl/ui/ui.py
cyberdrop_dl/utils/args/browser_cookie_extraction.py
cyberdrop_dl/utils/utilities.py
pyproject.toml

1. Add `(COM8) flake8-commas linter`, `(RUF) RUF specific fixes` and `(Q) flake8-quotes` to ruff config rules
2. Run ruff again to fix the errors from the last few PRs
Hopefully this is the last PR about formatting. Future PRs should not be approved until they pass the ruff check.

ci: update ruff rules + apply ruff fixes again

---

cyberdrop_dl/utils/utilities.py

Fixed development version check code & fixed a small typo.

Fix version check code

---

cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py

Cyberfile now uses the same ajax entrypoint for password protected files and folders

fix: password protected files (cyberfile)

---

cyberdrop_dl/managers/manager.py
cyberdrop_dl/ui/program_ui.py
cyberdrop_dl/ui/prompts/user_prompts.py

1. Fix `client_manager` not being closed at exit
2. Fix CDL opening default `URLs.txt` file instead of actual `URLs.txt`  (UI "Edit URLs.txt" option)

fix: minor fixes

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/scraper/crawler.py

check if a download should be skipped before making any request

refactor: move skip_host/only_host check up in the logic

---

cyberdrop_dl/managers/log_manager.py

fix: do not run update_last_forum_post if input_file is html

---

cyberdrop_dl/managers/realdebrid_manager.py

fix: do not startup real_debrid unless enabled

---

.github/workflows/ruff.yaml
cyberdrop_dl/clients/hash_client.py
cyberdrop_dl/main.py
cyberdrop_dl/scraper/filters.py
cyberdrop_dl/utils/data_enums_classes/hash.py
cyberdrop_dl/utils/database/tables/hash_table.py
poetry.lock
pyproject.toml

1. force update poetry ruff version to 0.8.0
2. pin ruff gh-action version to v0.8.0
3. apply fixes for new ruff rules

ci: update ruff action

---

cyberdrop_dl/clients/hash_client.py

- skip any zero sized files
- skip any part files

fix: handle edge case were zero sized files are being added to db

---

cyberdrop_dl/clients/hash_client.py

don't remove files if --ignore-history flag is on

fix: don't dedupe on ignore

---

cyberdrop_dl/managers/client_manager.py

prevent going down function at success status codes, when downloading bool is True

fix: downloads reaching eof at 0 bytes

---

cyberdrop_dl/managers/download_manager.py

- syncs the free space on system and the free space required by user to both be in bytes

fix: free space not be calculated in bytes

---

cyberdrop_dl/managers/client_manager.py

Many functions require that the http_check_status function either returns early or raise an exception
The easiest thing would be to mostly revert the file back to the original as that has been tested
The only downside is not raising an error for cloudflare will mean those pages will be cached, but that might make it easier to find a solution

revert cloudflare changes

---

cyberdrop_dl/utils/logger.py

Only the main log file is redacted (calls to the `log` function).
Debug log file is unchanged.
Messages printed to the console are unchanged
The other log files never use paths so it not necessary to redact them

refactor: redact username from logs

---

cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
cyberdrop_dl/scraper/crawlers/leakedmodels_crawler.py
cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
cyberdrop_dl/scraper/crawlers/xbunker_crawler.py

handle bare forums URLs
Base is 5.7.2. Can't be merge into current master

fix: forum post parsing

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/managers/client_manager.py
cyberdrop_dl/scraper/crawlers/gofile_crawler.py
cyberdrop_dl/utils/sorting.py

- Also sets requests limit to 100/min
- Fixes #360

fix: update gofile crawler to new design

---

cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
cyberdrop_dl/scraper/crawlers/xenforo_crawler.py

Added a link filter to the f95zone crawler so that we can convert thumbnails to their full resolution counterparts, or ignore them altogether if we decide to later on.

Add custom link filter to xenforo crawler

---

cyberdrop_dl/scraper/crawlers/coomer_crawler.py
cyberdrop_dl/scraper/crawlers/kemono_crawler.py
cyberdrop_dl/scraper/filters.py
pyproject.toml

Shift the cache when new posts are detected on a Coomer or Kemono profile, instead of entirely invalidating it.

Implement Coomer & Kemono Cache Shifting

---

cyberdrop_dl/scraper/crawlers/coomer_crawler.py
cyberdrop_dl/scraper/crawlers/kemono_crawler.py
cyberdrop_dl/scraper/crawlers/nekohouse_crawler.py

- Depends on #385 
- Fixes #256

fix: handle posts with missing data (nekohouse)

---

cyberdrop_dl/utils/transfer/transfer_hash_db.py
pyproject.toml

Ignore duplicate file entries from old database
- Fixes #390

fix: v5 to v6 database transfer 

---

cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py

Some URLs still use the old method to check if the password if valid

fix: fallback to old file password check (cyberfile)

---

cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
cyberdrop_dl/scraper/crawlers/xxxbunker_crawler.py

fix: sanitize custom filenames

---

cyberdrop_dl/utils/sorting.py
pyproject.toml

There is a bug where the videoprops will detect average frames as zero, and that causes issues when calling fraction
, as it tries to compute 0/0
Also I believe this expection was causing sorting to not progress, and crashed the program it seems

Fix:  solution for average frames being zero

---

cyberdrop_dl/utils/transfer/db_setup.py

fix: do not try to transfer `downloader.log` (v4 import)

---

cyberdrop_dl/managers/client_manager.py
cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawlers/pixhost_crawler.py

Added a pixhost.to crawler that supports albums & images.

Create Pixhost.to crawler

---

cyberdrop_dl/config_definitions/authentication_settings.py
cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawlers/allporncomix_crawler.py
cyberdrop_dl/scraper/filters.py

Add a xenforo crawler for https://forum.allporncomix.com
Closes #395

Feature: Add allporncomix crawler

---

cyberdrop_dl/managers/path_manager.py

Replace internal lists of media items with sets

fix: hashing

---

cyberdrop_dl/config_definitions/authentication_settings.py
cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawlers/allporncomix_crawler.py
cyberdrop_dl/scraper/crawlers/bellazon_crawler.py
cyberdrop_dl/scraper/crawlers/xenforo_crawler.py

Add xenforo scraping support for https://www.bellazon.com.

Feature: Add support for bellazon.com

---

cyberdrop_dl/main.py

fix: delete startup log file if empty

---

cyberdrop_dl/clients/hash_client.py
cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/utils/data_enums_classes/url_objects.py

Required to store them in sets. Fixes hashing after the changes from #437

fix: make `MediaItem` hashable

---

cyberdrop_dl/scraper/crawlers/chevereto_crawler.py

feat: add videos support (chevereto)

---

cyberdrop_dl/main.py
cyberdrop_dl/utils/yaml.py

Windows does not allow deleting files that are open so we need to close the file before removing it.

Fix: Windows Startup Logger Permission Error

---

cyberdrop_dl/managers/client_manager.py
cyberdrop_dl/scraper/crawlers/xenforo_crawler.py

- Fix `DDos-Guard` detection
- Fix `post_name` for the Xenforo crawler

fix: DDoS-Guard check

---

CHANGELOG.md
docs/reference/supported-websites.md
pyproject.toml

- Assumes #460 will be merged before release

docs: wiki and changelog updates for v6.2.0 release

---

CHANGELOG.md
cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py

fix: handle bunkr reinforced links

---

cyberdrop_dl/scraper/crawlers/coomer_crawler.py

This is a little scuffed so it may not be worth adding.

Add Coomer search crawler

---

cyberdrop_dl/config_definitions/global_settings.py
cyberdrop_dl/utils/transfer/transfer_v4_config.py

- See https://github.com/jbsparrow/CyberDropDownloader/pull/491#issuecomment-2603506657

refactor: override min required free space on startup 

---

cyberdrop_dl/scraper/crawler.py

This fixes an issue with coomer not getting the full url for download

Coomer fix

---

CHANGELOG.md
cyberdrop_dl/managers/client_manager.py
cyberdrop_dl/scraper/crawlers/imgur_crawler.py
docs/reference/supported-websites.md

Also adds support for gallery URLs

fix: imgur crawler

---

cyberdrop_dl/scraper/crawlers/kemono_crawler.py

Add search crawler for Kemono.su.

Add Kemono search crawler

---

cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/bunkrr_albums_io_crawler.py

- Add support for search results
- Added as debug crawler

feat: add support for bunkr-albums.io

---

cyberdrop_dl/main.py

log file is already closed at that point

fix: do not use startup logger on keyboard interupt

---

cyberdrop_dl/utils/database/tables/history_table.py

fix: db chevereto domains conflicts

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/clients/errors.py
cyberdrop_dl/config_definitions/config_settings.py
cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/managers/real_debrid/api.py
cyberdrop_dl/ui/progress/file_progress.py
cyberdrop_dl/utils/utilities.py
docs/reference/configuration-options/global-settings/rate-limiting-options.md
docs/reference/configuration-options/settings/runtime_options.md

feat: skip slow downloads

---

CHANGELOG.md
cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawlers/imagebam_crawler.py
cyberdrop_dl/scraper/crawlers/imageban_crawler.py
docs/reference/supported-websites.md

This is a completely new crawler. The old site and domain no longer exists

fix: imagebam crawler

---

cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py

- Fix folder structure for nested items
- Fix missing album titles
- Use canonical URLs for database

fix: Tokyomotion fixes

---

CHANGELOG.md
cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawlers/pornpics_crawler.py
docs/reference/supported-websites.md

feat: add pornpics support

---

docs/reference/cli-arguments.md

Closes #498.
Update CLI Overview to include new CLI arguments.

Update CLI Overview Docs

---

cyberdrop_dl/clients/errors.py
cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/ui/progress/statistic_progress.py

- Drop regex and hardcode some common errors instead
- Fixes #537

fix: prettify errors

---

CHANGELOG.md
cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawlers/eightmuses_crawler.py
docs/reference/supported-websites.md

Add a crawler for https://comics.8muses.com

Feature: Add comics.8muses.com crawler

---

cyberdrop_dl/scraper/crawlers/nudostartv_crawler.py
cyberdrop_dl/utils/database/tables/history_table.py

- Fix nudostart.tv base domain
- Send images to the queue instead of awaiting them
- Add support for image URLs as input URLs

fix: nudostar.tv crawler

---

cyberdrop_dl/utils/cookie_management.py
docs/reference/configuration-options/settings/browser_cookies.md

- See: https://github.com/borisbabic/browser_cookie3/issues/210

refactor: drop support for all chromium based browsers on Windows

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/bunkrr_albums_io_crawler.py
cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
cyberdrop_dl/scraper/crawlers/ehentai_crawler.py
cyberdrop_dl/scraper/crawlers/eightmuses_crawler.py
cyberdrop_dl/scraper/crawlers/hotpic_crawler.py
cyberdrop_dl/scraper/crawlers/imagebam_crawler.py
cyberdrop_dl/scraper/crawlers/luscious_crawler.py
cyberdrop_dl/scraper/crawlers/pixhost_crawler.py
cyberdrop_dl/scraper/crawlers/pornpics_crawler.py
cyberdrop_dl/scraper/crawlers/realbooru_crawler.py
cyberdrop_dl/scraper/crawlers/reddit_crawler.py
cyberdrop_dl/scraper/crawlers/rule34xxx_crawler.py
cyberdrop_dl/scraper/crawlers/scrolller_crawler.py
cyberdrop_dl/scraper/crawlers/tiktok_crawler.py
cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
cyberdrop_dl/scraper/crawlers/twitter_images_crawler.py
cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
cyberdrop_dl/scraper/crawlers/xxxbunker_crawler.py
cyberdrop_dl/scraper/jdownloader.py
cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/utils/database/tables/history_table.py
cyberdrop_dl/utils/sorting.py

- Related to #522
- Related to #561

refactor: increase verbosity of some processes + fix some log levels

---

cyberdrop_dl/ui/program_ui.py

refactor: enable UI sort option

---

cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/ui/progress/downloads_progress.py

refactor: show queued files in UI progress

---

cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py

- Complete refactor of the entire crawler
- Add a custom function to handle suffix replacement of encoded URLs
- Add `wings` and `bacon` as new CDNs
- Fixes #589

refactor: bunkr crawler

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/utils/javascript.py

Functions to parse information from the javascript in a soup
Also remove double spaces from titles on all crawlers
I will use these on multiple new crawlers

refactor: add javascript utils

---

cyberdrop_dl/scraper/crawlers/celebforum_crawler.py

Download full quality images from celebforum.to instead of thumbnails.
Closes #581.

Fix Celebforum Images

---

cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py

fix: handle deleted files (cyberfile)

---

cyberdrop_dl/main.py
cyberdrop_dl/managers/live_manager.py
cyberdrop_dl/managers/progress_manager.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/ui/progress/downloads_progress.py
cyberdrop_dl/utils/args.py

- Needs #530
- Needs #586 
- Resolves #483

refactor: show simplified progress with `--no-ui`

---

README.md

https://github.com/jbsparrow/CyberDropDownloader/issues/639

[chore] change to getting started guide

---

cyberdrop_dl/config_definitions/pydantic/custom_types.py

- Same as #605
- The changes from the original PR were deleted with a forced push
- Fixes #644

fix: `yarl.URL` json serialization

---

cyberdrop_dl/scraper/filters.py
cyberdrop_dl/scraper/scraper.py

feat: try to download files from unsupported forums

---

cyberdrop_dl/managers/client_manager.py

Some attributes are missing sometimes. Which makes `DDoSGuard` errors raise as `Unknown`
I haven't really debug _why_ they are missing but at least this will handle the error properly

fix: handle malformed responses (flaresolverr)

---

cyberdrop_dl/config_definitions/config_settings.py
docs/reference/configuration-options/settings/browser_cookies.md

- Use a placeholder to represent all sites instead of the actual list of domains
- ~~Silently drop any unknown domain~~ Allow any domain
- Fixes #643

fix: handle changes in supported sites (config values)

---

cyberdrop_dl/utils/args.py

Running CDL with `--help` inside an IDE will update the CLI overview

refactor: auto update wiki CLI overview

---

cyberdrop_dl/scraper/crawlers/gofile_crawler.py

Trying to fix `Error-rateLimit`. I haven't tested this, but it should help. It's a 60% reduction
- Proper fix will be with #557

refactor: reduce gofile request limiter

---

cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/scraper/crawlers/reddit_crawler.py
cyberdrop_dl/utils/data_enums_classes/url_objects.py

- Use a more robust approach to get the final file in redirects
- Fix referer being the same as the url of the file
- Fix formatting of log messages for referer
- Add `origin` and `parent` methods to `ScrapeItem`

fix: reddit referers

---

cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
cyberdrop_dl/scraper/crawlers/xenforo_crawler.py

Set custom name for the session cookie on subclasses (xenforo)

fix: false positive `FailedLogin` errors

---

cyberdrop_dl/clients/errors.py
cyberdrop_dl/main.py
cyberdrop_dl/managers/config_manager.py
cyberdrop_dl/utils/apprise.py
cyberdrop_dl/utils/constants.py
cyberdrop_dl/utils/yaml.py

Also modified the error footer to tell the user to delete the file if they don't know how to fix it

refactor: better error messages for invalid configs

---

cyberdrop_dl/config_definitions/config_settings.py
cyberdrop_dl/managers/config_manager.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/scraper/crawler.py

refactor: validate regex at startup

---

cyberdrop_dl/scraper/crawlers/xenforo_crawler.py

- Raise as `422` instead of Unknown
- Log details to debug log file
- Fix and ignore some type hints

refactor: log unexpected responses from forums

---

cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/chevereto_crawler.py

- Don't remove trailing slashes from parsed pages
- Refactor static method as normal functions
- Add missing type hints
- Fixes #599

fix: regression - do not remove trailing slash from URLs (chevereto)

---

cyberdrop_dl/scraper/crawlers/tiktok_crawler.py

Fix TikTok crawler returning 403 on all downloads.

Fix TikTok Crawler

---

CHANGELOG.md

docs: wiki and changelog updates for v6.6.1 release

---

cyberdrop_dl/config_definitions/authentication_settings.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
cyberdrop_dl/utils/cookie_management.py

Make cookie files mandatory for forums, but only if they require login
- Resolves #474
- Resolves #471

refactor: deprecate forum auth (username and password)

---

cyberdrop_dl/config_definitions/config_settings.py

fix(config): do not overwrite user provided regex

---

cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawlers/yandex_disk_crawler.py
cyberdrop_dl/utils/data_enums_classes/url_objects.py

- Supports files and folders, but not nested folder

feat: add yandex disk support

---

cyberdrop_dl/scraper/crawlers/chevereto_crawler.py

URLs are now decrypted at runtime with javascript. This bypasses that

fix: get URL from encrypted link (jpg5)

---

cyberdrop_dl/managers/progress_manager.py
cyberdrop_dl/ui/progress/file_progress.py
cyberdrop_dl/ui/progress/scraping_progress.py
cyberdrop_dl/utils/args.py

Show CDL in a portrait layout if the console height is at least 20% larger that its width

feat: add portrait layout

---

cyberdrop_dl/managers/client_manager.py

- Fix user-agent mismatch message
- Use a 5 minutes timeout to create the session
- Use the config timeout for everything else
- Always use the created session
- Add type hints and ignores
- See: https://github.com/jbsparrow/CyberDropDownloader/pull/729#issuecomment-2692275783

fix: flaresolverr integration

---

cyberdrop_dl/scraper/crawlers/xenforo_crawler.py

- Add error handle at post level
- Define `process_child` to handle individual items in a post
- Add error handle to `process_child`
- Resolves #640

fix: invalid URL handle (xenforo)

---

cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py

Use the streaming API to get the download URL (when possible)

fix: 403 on some files (bunkr)

---

cyberdrop_dl/scraper/crawlers/chevereto_crawler.py

- Method used in #726 no longer works
- Requires 1 aditional request per image
- This also fixes date parsing of images that are part of an album

fix: get URL from encrypted link (update) (jpg5)

---

cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/onedrive_crawler.py

- Support files, folders and nested folders
- Does not require API credentials
- Only works with "anyone can access" links

feat: add OneDrive support

---

cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawlers/sex_dot_com_crawler.py

Added a crawler for sex.com, supports shorts profiles e.g. www.sex.com/en/shorts/beauty_mia
Does not support downloading full videos as those are streamed using HLS.

Add crawler for sex.com

---

CHANGELOG.md
cyberdrop_dl/ui/prompts/user_prompts.py

Add an option to import cookies from all supported websites, and remove browsers that aren't supported on the user's operating system.

Improve Cookie Import

---

cyberdrop_dl/scraper/crawlers/eporner_crawler.py

fix: handle deleted videos (eporner)

---

cyberdrop_dl/main.py
cyberdrop_dl/utils/logger.py

refactor: log requests cache activity

---

cyberdrop_dl/scraper/crawlers/sex_dot_com_crawler.py

fix: sex.com URL parsing

---

cyberdrop_dl/scraper/crawlers/google_drive_crawler.py

fix: handle invalid URLs (google drive)

---

cyberdrop_dl/scraper/crawlers/chevereto_crawler.py

- 80% reduction
- Related to #772

refactor: reduce rate limit (jpg5)

---

cyberdrop_dl/managers/client_manager.py

fix: DDoSGuard check from pages with no title

---

cyberdrop_dl/scraper/crawlers/onedrive_crawler.py

Used by OneDrive for business and newer OneDrive personal accounts

feat: add support for SharePoint backend links (OneDrive)

---

cyberdrop_dl/scraper/crawlers/yandex_disk_crawler.py

fix: handle single file share links (yandex)

---

cyberdrop_dl/scraper/crawlers/dirtyship_crawler.py

fix: tag and category support (dirtyship)

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawlers/send_now_crawler.py

feat: add send.now support

---

cyberdrop_dl/managers/client_manager.py
cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawlers/nhentai_crawler.py
cyberdrop_dl/utils/logger.py

feat: add nhentai support

---

cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawlers/bestprettygirl_crawler.py

- Needs #800 for pagination
- Needs #801 for videos

feat: add bestprettygirl support

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/pmvhaven_crawler.py
cyberdrop_dl/utils/utilities.py

feature: Add crawler for pmvhaven.com (#699)

feature: Add crawler for pmvhaven.com

---

cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/motherless_crawler.py

feat: add motherless support

---

cyberdrop_dl/downloader/downloader.py

refactor: make downloader return success

---

cyberdrop_dl/main.py

Pressing `Ctrl` + `C` will cancel all crawlers, print stats and send webhook / apprise notifications instead of just quitting

refactor: add graceful shutdown

---

cyberdrop_dl/clients/hash_client.py

perf: async delete files (dedupe)

---

cyberdrop_dl/config_definitions/custom/types.py
cyberdrop_dl/config_definitions/custom/validators.py

yarl.url still have issues serializing on python 3.12

re-add line

---

cyberdrop_dl/crawlers/__init__.py
cyberdrop_dl/crawlers/crawler.py
cyberdrop_dl/crawlers/xhamster.py
cyberdrop_dl/utils/javascript.py
cyberdrop_dl/utils/utilities.py

feat: add xhamster support

---

cyberdrop_dl/clients/scraper_client.py

Some dependencies are not available on Android. See:  https://github.com/jbsparrow/CyberDropDownloader/pull/822#issuecomment-2750176766

fix: catch errors on `curl_cffi` import

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/managers/client_manager.py

fix: request response / curl references

---

cyberdrop_dl/crawlers/bunkrr.py

- Fixes #848, but it will (potentially) trigger lot of additional requests

fix: always deep scrape albums (bunkr)

---

cyberdrop_dl/crawlers/bunkrr.py

Need to be specific of which image inside theItem.
Fixes #848

fix: bunkr album scraper changes

---

cyberdrop_dl/crawlers/eporner.py

- Add photo support
- Add gallery support
- Add profile support
- Resolves #809

feat: add profile support (eporner)

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/clients/hash_client.py
cyberdrop_dl/crawlers/crawler.py
cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/managers/path_manager.py
cyberdrop_dl/utils/data_enums_classes/url_objects.py
cyberdrop_dl/utils/database/tables/history_table.py
cyberdrop_dl/utils/ffmpeg.py
cyberdrop_dl/utils/utilities.py

CDL downloads each fragment and them mux them together with ffmpeg.
- Related to #807

feat: add hls (m3u8) support

---

cyberdrop_dl/crawlers/xenforo/xenforo.py

- Update regex to extract URLs from embeds
- Refactor `process_children` to make clear it handles both strings and tags
- Fixes #828

fix: embed parsing (xenforo)

---

cyberdrop_dl/managers/client_manager.py
cyberdrop_dl/utils/utilities.py

Fixes `TypeError: Incoming markup is of an invalid type`

fix: get soup from non curl responses

---

cyberdrop_dl/crawlers/xenforo/titsintops.py

Fix titsintops crawler and cookie extraction.

Fix: Titsintops crawler

---

cyberdrop_dl/managers/download_manager.py
cyberdrop_dl/managers/storage_manager.py

fix: free space check when using network drives (windows)

---

cyberdrop_dl/crawlers/ashemaletube.py

There was a small modification in the ashemaletube site's models category changing it to creators or pornstars.

fix: [ashemaletube] site's models category changed to pornstars or creators

---

cyberdrop_dl/crawlers/thisvid.py

While scraping user's profile I noticed it was downloading same videos again.

fix: use canonical URL for videos (thisvid)

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/config_definitions/global_settings.py
cyberdrop_dl/downloader/downloader.py

Adds a `jitter` config option to wait a random extra number of seconds in between downloads

feat: add jitter inbetween downloads

---

cyberdrop_dl/crawlers/ashemaletube.py

Related to commit dcec3ed, that was causing an JSONDecodeError.

bug: [ashemaletube] fixing json parsing

---

cyberdrop_dl/crawlers/ashemaletube.py

After dcec3ed, the title only included the model's name.

fix: [ashemaletube] fixing title creation

---

cyberdrop_dl/crawlers/crawler.py

- Define a `parse_date` method in the base crawler to get a date from a string. This is to remove code duplication. Almost all crawlers have to parse dates.
- Define a `parse_soup_date` as a helper method to get the date from a tag and them call `parse_date`
- Add shorcut to `log`, `log_debug` and `utils` from within the crawler
I also made it lenient and ignore any errors. The crawler should continue even if it was unable to get a date. 
This PR only defines the methods. None of the crawlers are actually using them

refactor: make the base crawler parse all dates

---

CHANGELOG.md
cyberdrop_dl/utils/ffmpeg.py
pyproject.toml

fix: better handling of missing ffmpeg

---

cyberdrop_dl/crawlers/bestprettygirl.py

See commit history for details

fix: crawler fixes (bestprettygirls)

---

cyberdrop_dl/crawlers/ashemaletube.py

See commit history for details

fix: crawler fixes (ashemaletube)

---

cyberdrop_dl/crawlers/chevereto.py

fix: iter items on chevereto profiles

---

cyberdrop_dl/crawlers/rule34vault.py
cyberdrop_dl/crawlers/rule34xyz.py

Also makes rule34xyz inherit from rule34vault

fix: crawler fixes (rule34xyz , rule34vault)

---

cyberdrop_dl/crawlers/coomer.py
cyberdrop_dl/crawlers/crawler.py
cyberdrop_dl/crawlers/kemono.py
cyberdrop_dl/crawlers/xenforo/xenforo.py
cyberdrop_dl/managers/cache_manager.py
cyberdrop_dl/scraper/filters.py

refactor: let crawlers define their own cache filter

---

tests/test_startup.py

test: add startup tests

---

cyberdrop_dl/crawlers/bunkrr.py

See: https://github.com/jbsparrow/CyberDropDownloader/discussions/932#discussioncomment-12916370

fix: No file extension from og filename (bunkr)

---

cyberdrop_dl/crawlers/bunkrr.py

fix: get filename from og properties (bunkr)

---

cyberdrop_dl/managers/storage_manager.py

fix: ignore errors while getting available mountpoints

---

cyberdrop_dl/crawlers/__init__.py
cyberdrop_dl/crawlers/archivebate.py
cyberdrop_dl/crawlers/mixdrop.py

- Only supports individual videos in archivebate. I tried a couple of ways to support profiles but all of them require javascript.
- Resolves #549

feat: add Mixdrop + archivebate support

---

cyberdrop_dl/crawlers/doodstream.py

- Add more supported domains
- Use the same host as the input URL for the API call
- Related to #935

refactor: update supported domains (doodstream)

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/crawlers/crawler.py
cyberdrop_dl/crawlers/generic.py
cyberdrop_dl/director.py
cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/scraper/jdownloader.py
cyberdrop_dl/ui/program_ui.py
cyberdrop_dl/utils/cookie_management.py
cyberdrop_dl/utils/utilities.py

Fixes "Unknown" return type and params in IDE's signature information box

style: fix signature of functions that use wrappers

---

cyberdrop_dl/crawlers/thisvid.py

Example: https://thisvid.com/videos/she-knows-whats-up

fix: handling videos with unknown resolution (Thisvid)

---

cyberdrop_dl/crawlers/thisvid.py

Example: https://thisvid.com/albums/little-bit-of-myself/

feat: add support to albums (ThisVid)

---

cyberdrop_dl/managers/client_manager.py

refactor: improve cloudflare captcha detection

---

cyberdrop_dl/crawlers/reddit.py
cyberdrop_dl/crawlers/xenforo/xenforo.py

See: https://github.com/jbsparrow/CyberDropDownloader/pull/960#issuecomment-2840176613

fix: add separate post title (xenforo, reddit)

---

cyberdrop_dl/crawlers/reddit.py

fix: gif downloads (reddit)

---

cyberdrop_dl/utils/sorting.py

fix: remove leftover filedate reference

---

cyberdrop_dl/managers/config_manager.py

refactor: force remove unsupported entries (auth config file)

---

cyberdrop_dl/crawlers/__init__.py
cyberdrop_dl/crawlers/box_dot_com.py

Support for files, folders and nested folders

feat: add box.com support

---

cyberdrop_dl/managers/client_manager.py

refactor: check DDoS-Guard even on successful pages

---

cyberdrop_dl/director.py

I removed this when i added textual. Adding it back until textual works properly
- Original PR: #820

refactor: add graceful shutdown (again)

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/crawlers/_chevereto.py
cyberdrop_dl/crawlers/bunkrr.py
cyberdrop_dl/crawlers/cyberdrop.py
cyberdrop_dl/crawlers/cyberfile.py
cyberdrop_dl/crawlers/dropbox.py
cyberdrop_dl/crawlers/e621.py
cyberdrop_dl/crawlers/generic.py
cyberdrop_dl/crawlers/gofile.py
cyberdrop_dl/crawlers/google_drive.py
cyberdrop_dl/crawlers/imgur.py
cyberdrop_dl/crawlers/jpg5.py
cyberdrop_dl/crawlers/kemono.py
cyberdrop_dl/crawlers/luscious.py
cyberdrop_dl/crawlers/onedrive.py
cyberdrop_dl/crawlers/pmvhaven.py
cyberdrop_dl/crawlers/reddit.py
cyberdrop_dl/crawlers/redgifs.py
cyberdrop_dl/crawlers/send_now.py
cyberdrop_dl/crawlers/sex_dot_com.py
cyberdrop_dl/crawlers/wetransfer.py
cyberdrop_dl/crawlers/xenforo/celebforum.py
cyberdrop_dl/crawlers/xenforo/f95zone.py
cyberdrop_dl/crawlers/xenforo/xenforo.py
cyberdrop_dl/crawlers/yandex_disk.py

- Fixes for the changes in #950

fix: crawlers http calls

---

cyberdrop_dl/crawlers/doodstream.py

refactor: download from the same host as the initial response (doodstream)

---

cyberdrop_dl/crawlers/kemono.py

- Move last page logic out of pager
- Simplify URL parsing
- Split discord server and channel methods

fix: `StopIteration` error when reaching the last page (Kemono)

---

.github/workflows/apprise.yml
.github/workflows/ci.yml
README.md
poetry.lock
tests/conftest.py
tests/test_cli.py
tests/test_m3u8.py
tests/test_startup.py

- Fix imports on some tests
- Move apprise to its own workflow
- Only run apprise tests if the apprise module changed
- Run tests on every pull request to `dev`

test: update tests scope

---

cyberdrop_dl/managers/progress_manager.py

refactor: show version at screen bottom

---

cyberdrop_dl/crawlers/_chevereto.py
cyberdrop_dl/crawlers/jpg5.py

_proccess_media_item was never called. I rewrote it to handle url xor encryption.
Closes #928

fix: handling encrypted image urls (jpg5)

---

CHANGELOG.md
cyberdrop_dl/crawlers/crawler.py
cyberdrop_dl/utils/utilities.py
tests/test_unicode_emoji_sanitization.py

fix: sanitizing title to avoid illegal byte sequence error

---

cyberdrop_dl/clients/scraper_client.py

response_to_soup wasn't handling javascript content type

fix: gofile token extraction

---

cyberdrop_dl/director.py

Does not work on Windows. Raises exception

fix: disable graceful shutdown

---

cyberdrop_dl/crawlers/_chevereto.py
cyberdrop_dl/crawlers/crawler.py

- Fix thumbnail extraction
- Fix direct file fetch filter
- Fix videos canonical URL parsing from thumbnails
- Fix check album results
- Add back logic to download from thumbnail

fix: profile downloads (chevereto)

---

cyberdrop_dl/crawlers/crawler.py
cyberdrop_dl/crawlers/thisvid.py

Crawler was broken by #1008
Fixed thumbnail parsing when img tag has embedded image in src.

fix: thisvid crawler

---

cyberdrop_dl/crawlers/_kemono_base.py

fix: parsing individual post URLs (Kemono)

---

cyberdrop_dl/clients/hash_client.py
cyberdrop_dl/managers/progress_manager.py
cyberdrop_dl/ui/program_ui.py
cyberdrop_dl/ui/prompts/basic_prompts.py

fix: only print dedupe stats (menu option)

---

cyberdrop_dl/crawlers/__init__.py
cyberdrop_dl/crawlers/vbulletin/__init__.py
cyberdrop_dl/crawlers/vbulletin/_vbulletin.py
cyberdrop_dl/crawlers/vbulletin/vipergirls.py
cyberdrop_dl/crawlers/xenforo/xenforo.py
tests/crawlers/test_vbulletin.py

We do not support all of the image hosts they use, but the crawler itself works

feat: add vipergirls support

---

cyberdrop_dl/crawlers/_kemono_base.py
cyberdrop_dl/crawlers/crawler.py

Fetch the entire list of creators at startup and keep it in memory.
The list is 24MB for coomer and 11 MB for Kemono

perf: get all creators at startup (kemono)

---

cyberdrop_dl/crawlers/ashemaletube.py

The site changed the video script slightly, and most of the videos now are served as hls.

fix: handling new player script format and HLS videos (ashemaletube)

---

cyberdrop_dl/crawlers/_kemono_base.py
cyberdrop_dl/crawlers/coomer.py

fix: coomer not fetching usernames at startup

---

cyberdrop_dl/crawlers/beeg.py

best_format.url always changes.

fix: properly caching downloaded videos urls (beeg)

---

cyberdrop_dl/crawlers/_forum.py
cyberdrop_dl/crawlers/crawler.py
cyberdrop_dl/crawlers/redgifs.py
cyberdrop_dl/crawlers/wordpress/_wordpress.py
cyberdrop_dl/data_structures/url_objects.py

See: https://github.com/jbsparrow/CyberDropDownloader/issues/1116#issuecomment-3040525009
- Resolves #1116

refactor: always reset a scrape item before sending it to new crawler

---

cyberdrop_dl/crawlers/pornhub.py

https://github.com/jbsparrow/CyberDropDownloader/issues/1139#issuecomment-3041442245
- Resolves #1139

refactor: fallback to hls for newer videos (PornHub)

---

cyberdrop_dl/crawlers/crawler.py
cyberdrop_dl/crawlers/redgifs.py
cyberdrop_dl/utils/database/tables/history_table.py

- Use stricter URL matching
- Handle embed URLs
- Handle direct links
- Use canonical URL for database

perf: add canonical URL for `check_complete_by_referer` (redgifs)

---

cyberdrop_dl/crawlers/wordpress/__init__.py
cyberdrop_dl/crawlers/wordpress/_wordpress.py
cyberdrop_dl/crawlers/wordpress/everia.py
cyberdrop_dl/env.py
cyberdrop_dl/exceptions.py
cyberdrop_dl/utils/css.py
cyberdrop_dl/utils/utilities.py

- Handle more cases with the base html wordpress crawler
- Handle validation errors with `error_handling_wrapper`
- Add everia.club support

feat: add everia support

---

cyberdrop_dl/crawlers/crawler.py

fix: check valid URL after assigning a task id

---

cyberdrop_dl/crawlers/jpg5.py
cyberdrop_dl/utils/database/tables/history_table.py

feat: add jpg6 support

---

cyberdrop_dl/crawlers/pixhost.py

- Fix source URL creation
- Match URLs exactly
- Fixes #1184

fix: albums downloads (pixhost)

---

cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/managers/config_manager.py
cyberdrop_dl/utils/apprise.py
poetry.lock
pyproject.toml

https://github.com/jbsparrow/CyberDropDownloader/pull/1205#issuecomment-3146954973

fix: only install pywin32 on cpython 

---

cyberdrop_dl/config/auth_model.py
cyberdrop_dl/crawlers/xxxbunker.py
tests/crawlers/test_cases/xxxbunker.py

- Downloading videos no longer requires an account
- Remove rate limiting logic
- Remove date parsing logic
- Fix playlist videos selector
- Fix playlist pagination

refactor: rework extractor (xxxbunkr)

---

cyberdrop_dl/crawlers/_chevereto.py
cyberdrop_dl/crawlers/crawler.py
cyberdrop_dl/crawlers/jpg5.py
tests/crawlers/test_cases/jpg5.py

refactor: transform album subfolder URLs (chevereto)

---

cyberdrop_dl/data_structures/url_objects.py

do not re-add domain name on subfolders of the same crawler

refactor: do not re-add domain name on subfolders

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/clients/hash_client.py
cyberdrop_dl/crawlers/_forum.py
cyberdrop_dl/crawlers/_kemono_base.py
cyberdrop_dl/director.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/managers/storage_manager.py
cyberdrop_dl/utils/logger.py
cyberdrop_dl/utils/sorting.py
cyberdrop_dl/utils/utilities.py

refactor: update formatting of log messages

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/crawlers/nhentai.py
tests/crawlers/test_cases/nhentai.py

fix: gallery downloads (nhentai)

---

cyberdrop_dl/crawlers/eporner.py

fix: ignore invalid json (eporner)

---

cyberdrop_dl/crawlers/toonily.py
tests/crawlers/test_cases/toonily.py

refactor: update crawler (toonily)

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/crawlers/twitter_images.py

One issue is that the file will always have a `.png` extension, even if it is a jpeg

refactor: try to download original quality (twitter images)

---

cyberdrop_dl/crawlers/xhamster.py
tests/crawlers/test_cases/xhamster.py

- Disable title translations
- Handle galleries with multiple pages
- fix user URL parsing and pagination

fix: handle videos without http sources (xhamster)

---

cyberdrop_dl/crawlers/tiktok.py

fix: nested folders for the same creator (tiktok)

---

cyberdrop_dl/crawlers/bunkrr.py
cyberdrop_dl/utils/css.py
tests/crawlers/test_cases/bunkr.py

fix: handle paginated albums (bunkr)

---

cyberdrop_dl/crawlers/_chevereto.py
cyberdrop_dl/crawlers/bunkrr.py
cyberdrop_dl/crawlers/xhamster.py
cyberdrop_dl/utils/utilities.py
tests/crawlers/test_cases/xhamster.py

fix: handle encrypted URLs (xhamster)

---

cyberdrop_dl/managers/client_manager.py

perf: use a weakref for file locks

---

cyberdrop_dl/crawlers/bunkrr.py
tests/crawlers/test_cases/bunkr.py

The page does not have any date
- Fixes #1331

fix: do no try to parse date of individual files (bunkr)
