cyberdrop_dl/managers/client_manager.py
pyproject.toml

Switch from using the ETag header (Bunkr does not include it anymore) to checking for the content length, which could have issues with other videos being of the same length, but it it extremely unlikely that any other video will have the exact same length.

Fix Bunkr Maintenance Video Detection

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/managers/client_manager.py
cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
pyproject.toml

Currently when maint file are encountered the add incomplete db step is skipped
change for the files to be added, and then throws an error to prevent downloading right after

allow bunkr maint files to still be added to database

---

cyberdrop_dl/scraper/crawlers/pixeldrain_crawler.py
cyberdrop_dl/utils/changelog.py
pyproject.toml

Implement the ability to scrape URLs from a PixelDrain text post and make them their own folder instead of various folders for each URL in the list.

Pixeldrain text scraping

---

README.md
cyberdrop_dl/managers/manager.py
cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/ui/prompts/general_prompts.py
cyberdrop_dl/ui/ui.py
cyberdrop_dl/utils/args/config_definitions.py
cyberdrop_dl/utils/changelog.py
cyberdrop_dl/utils/dataclasses/supported_domains.py
pyproject.toml

Removed the ability to scrape simpcity.su and added a disclaimer explaining the reasoning behind this decision as well as a docs page for it.
https://script-ware.gitbook.io/cyberdrop-dl/simpcity-support-dropped

Remove support for scraping SimpCity

---

cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/utils/changelog.py
poetry.lock
pyproject.toml

Added support for categorizing links in the URLs file.
Here is an example URLs.txt list:
```
https://example.com/file1.jpg
=== Test
https://example.com/file2.jpg
https://example.com/file3.jpg
===
https://example.com/file4.jpg
--- Test 2
https://example.com/file5.jpg
https://example.com/file6.jpg
===
https://example.com/file7.jpg
``` 
Those downloads will be categorized as followed: 
| Loose Files | Test | Test 2 |
|--------|--------|--------|
| file1.jpg | file2.jpg | file5.jpg |
| file4.jpg | file3.jpg | file6.jpg |
| file7.jpg | | |

Add link categorization to the URLs file.

---

cyberdrop_dl/managers/cache_manager.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/scraper/crawlers/simpcity_crawler.py

This adds a cache to the simpcity process to reduce load
- data is held in separate simpcity  cache file
- yaml was finky about saving the stringified html objects, so json was used 
- The caching is a little more complicated to save space, saving the entire page response takes about 300kb, however saving only the required information including posts data reduces this to around 15kb per page

add simpcity cache to reduce load

---

cyberdrop_dl/managers/cache_manager.py
cyberdrop_dl/managers/manager.py

The sqlite connection for the cache needs to be  close otherwise the script will hang

close cache sql

---

.gitignore
cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/main.py
cyberdrop_dl/managers/cache_manager.py
cyberdrop_dl/managers/live_manager.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/utils/utilities.py

1. Replaces built-in log file handler with rich handler for better tracebacks while debugging
2. Adds a basic function to show the total number of requests and the total number of cached responses during the run. Currently only used by the base `ScraperClient` class
3. Fixes return type of  `ScraperClient.get_text() -> str`
**Example log output**
[downloader.log](https://github.com/user-attachments/files/17157717/downloader.log)
[cyberdrop_dl_debug.log](https://github.com/user-attachments/files/17157718/cyberdrop_dl_debug.log)

add rich logger file handler

---

cyberdrop_dl/scraper/crawlers/redgifs_crawler.py
cyberdrop_dl/utils/changelog.py
cyberdrop_dl/utils/utilities.py
pyproject.toml

1. Replaces `Path.walk` with `os.walk` to remain compatible with python 3.11
2. Fixes minor bug where duplicate parents were added to new redgifs items.

Fix empty folders cleanup

---

cyberdrop_dl/scraper/crawlers/coomer_crawler.py
cyberdrop_dl/scraper/crawlers/kemono_crawler.py
cyberdrop_dl/utils/changelog.py
pyproject.toml

Fix coomer / kemono scrape_item parents
Fixes coomer and kemono `create_scrape_item`
Fixes #136 
---
> [!IMPORTANT]  
> Base if PR #137 . Merge that PR first before merging this one.

Fix coomer / kemono scrape_item parents

---

cyberdrop_dl/utils/utilities.py
pyproject.toml

Convert directories (`str`) back to `Path` objects before removing them
Related to #137

fix: purge_dir_tree

---

CHANGELOG.md
cyberdrop_dl/ui/ui.py
cyberdrop_dl/utils/utilities.py
docs/reference/supported-websites.md
pyproject.toml

1. Fixes crash if an unsupported URL have no parents
2. Always fetch an updated `CHANGELOG` from GH if a new version has been released on `Pypi`
3. Remove Simpcity from supported websites on the Wiki

Fix crash when unsupported URLs have no parents

---

cyberdrop_dl/clients/download_client.py

This will allow to filter the final host (the actual server with the file) with the `--skip-hosts` /  `--only-hosts` config
Use case: exclude specific bunkrr server

feat: apply skip/only hosts filter to final media_item URL

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/managers/cache_manager.py

1. Add `410 (Gone)` and `451 (Unavailable For Legal Reasons`) to cached responses
2. Add cache to `download_client` requests, excluding successful ones to not save file payloads in the database

Expand cache filter definition

---

cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
cyberdrop_dl/scraper/crawlers/leakedmodels_crawler.py
cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
cyberdrop_dl/scraper/crawlers/xbunker_crawler.py

Currently, all forum crawlers start from the first page of the thread, even if the `input URL` is from an specific post.
CDL just ignores any post that is lower that the post from the `input URL` (if any).
This PR forces the use of the input URL as the first scrape to reduce unnecessary requests.
Tested on SC and SMG. If the post was deleted or did no exists, both returned the first page of the thread so it should be safe.
There may be other edge cases were it fails and gets stuck in the while loop _(could not think of any)_ and so it needs testing.

feat: always start forum scrape from input URL

---

cyberdrop_dl/clients/scraper_client.py

1. Fixes flaresolverr middleware. `CachedSession.disabled()` does not return the session object so the request needs to be nested.
2. Allow the use of a full scheme flaresolverr URL.

Fix flaresolverr

---

CHANGELOG.md
cyberdrop_dl/scraper/crawlers/gofile_crawler.py

Users can include the password as a query parameter in the input URL, adding `?password=<URL_PASSWORD>` to it.
Example: `https://gofile.io/d/xUprGg?password=1234`
> [!NOTE]  
> `password` if not a valid query parameter for a regular GoFile link (only via the API) but it makes the implementation easy to use.

feat: add support for password protected GoFile URLs

---

CHANGELOG.md
cyberdrop_dl/managers/db_manager.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/utils/args/args.py
cyberdrop_dl/utils/args/config_definitions.py
cyberdrop_dl/utils/database/table_definitions.py
cyberdrop_dl/utils/database/tables/history_table.py
cyberdrop_dl/utils/database/tables/temp_referer_table.py
docs/reference/cli-arguments.md
docs/reference/configuration-options/settings.md

CDL will not download a file if the referer has already been scraped before.
CLI flag: `--skip-referer-seen-before`
The file (s) will always be skipped regardless of whether the referer was successfully scraped or not.
I was initially trying to implement `--skip-album-seen-before` but almost none of the crawlers were saving the `album_id` to the database. 
> [!NOTE]  
> This PR introduces a change to `cyberdrop.db`, creating a new table to store new referers found since the last run.

feat: add option to skip any referer scraped before

---

CHANGELOG.md
cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
pyproject.toml

1. Use a more restrictive css selector for videos in case they have no thumbnail
2. Update CDNs definitions
3. Throw `ScrapeFailure` if every filter fails
Fixes #183

fix: Bunkr edge cases

---

cyberdrop_dl/managers/path_manager.py
cyberdrop_dl/utils/args/config_definitions.py

1. add option to rotate log file names
if enabled, current `date-time` will be used as a suffix for each log file, in the format `YYMMDD_HHMMSS`
This will prevent overriding old log files
**Files that will be rotated**
| option                       | default_filename              |
|------------------------------|-------------------------------|
| download_error_urls_filename |  Download_Error_URLs.csv      |
| last_forum_post_filename     |  Last_Scraped_Forum_Posts.txt |
| main_log_filename            |  downloader.log               |
| scrape_error_urls_filename   |  Scrape_Error_URLs.csv        |
| unsupported_urls_filename    |  Unsupported_URLs.txt         |

feat: rotating log files 

---

cyberdrop_dl/managers/download_manager.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/xxxbunker_crawler.py
cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/utils/args/config_definitions.py

1. Add support for playlists, search results and video downloads on XXXBunker.com
Implementation requires the user to supply their `PHPSESSID` cookie value after they log in to the website. I tried to not use cookies and just download the src from the website but got many issues:
1. Videos have multiple sources available. The first one is the default and the website player goes to next one if down,  until an online src is found.
2. This requires the crawler to do the same, trying every source until a successful one is found. This is currently not possible without creating multiple entries in the database for each on the sources link
3. _A bunch_ of sources are down. During testing, I would say at least 70% of the videos got me a `404`. More common in older videos.
4. They have a pretty …

feat: add support for XXXBunker URLs 

---

cyberdrop_dl/managers/path_manager.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
cyberdrop_dl/scraper/crawlers/leakedmodels_crawler.py
cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
cyberdrop_dl/scraper/crawlers/xbunker_crawler.py
cyberdrop_dl/ui/prompts/settings_authentication_prompts.py
cyberdrop_dl/utils/args/browser_cookie_extraction.py

This is a global implementation to extract, read and use cookies for any of the supported sites.
Currently there is a branch to handle [SimpCity cookies for DDOS-guard ](https://github.com/jbsparrow/CyberDropDownloader/tree/DDOS-Guard-cookies)but the implementation is hard-coded into the crawler, making it not scalable. The crawler will also need to be modified if any of the cookie entry names changes.
This PR uses an external cookie jar for each of the supported domains. On startup, CDL will read the cookiejar of each crawler (if available) and apply all the cookies to the current session.
1. Auto scalable. No need to modify crawlers code.
2. Using it for file-hosts sites will solve most of the DDOS-guard challenges
Cookie file will be read-only and not updated during a run; This is by …

feat: universal cookie management for any supported site

---

cyberdrop_dl/utils/sorting.py

prevents move cd from crashing when permission is denied on when moving a file

handle permission errors when using move cd

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py

1. Add support for both file and folder protected URLs. Users can include the password as a query parameter in the input URL, adding `?password=<URL_PASSWORD>` to it. Example: `https://cyberfile.me/folder/xUGg?password=1234`
3. Minor typos and formatting fixes on the changelog
> [!NOTE]  
> `password` is not a valid query parameter for a regular Cyberfile link (only via the API) but it makes the implementation easy to use.

feat: add support for password protected Cyberfile URLs

---

cyberdrop_dl/managers/progress_manager.py
cyberdrop_dl/scraper/jdownloader.py
cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/ui/progress/statistic_progress.py
cyberdrop_dl/utils/args/config_definitions.py

1. Add option to autostart downloads on jdownloader as soon as they are sent from CDL
2. Add option to set a `download_dir` for jdownloader, diferent from CDL's. Useful if jdownloader is running on a diferent machine or inside docker
4. Now jdownloader will use the same download path that CDL would have used, instead of downloading all the files in the same folder. This path will be relative to `download_dir`
4. Add whitelist domain filter for jdownloader. Only domains in the whitelist will be sent. Any other URL will just be saved to `unsupported_URLs.txt`. An empty whitelist means `any domain` (every unsupported URL will be sent to jdownloader)
5. Show unsupported URLs stats at the end

feat: better jdownloader integration

---

CHANGELOG.md
cyberdrop_dl/ui/prompts/general_prompts.py
cyberdrop_dl/ui/ui.py
cyberdrop_dl/utils/utilities.py

Improve new version notifications to let the user know if there is a new testing version available if they are using a testing version.
CDL will also no longer notify you that there is a new version available when you are using a version that has not been uploaded to PyPi yet.

Improve new version notifications

---

cyberdrop_dl/managers/manager.py

Simplify and dynamically generate auth credentials report for the main log file. 
Added this to show if the new `XXXBunker` auth token was provided but it will also show any new site added in the future.

refactor: generate authentication info dynamically from config

---

cyberdrop_dl/main.py
cyberdrop_dl/utils/utilities.py

1. Only use console markdown when printing to console.
2. Increase default log width to fit large URLs in a single line

fix: remove console markdown from logs

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/managers/real_debrid/api.py
cyberdrop_dl/managers/real_debrid/errors.py
cyberdrop_dl/managers/realdebrid_manager.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/realdebrid_crawler.py
cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/utils/args/config_definitions.py
cyberdrop_dl/utils/dataclasses/url_objects.py
cyberdrop_dl/utils/utilities.py

Adds integration to handle URLs supported by [Real Debrid](https://real-debrid.com/)
Real Debrid is a download service which allow the user to download from many file hosters. You send them the URL of the file you want to download, they download the file to their servers and send you back a new URL pointing to their servers so you can download from them in real time, bypassing file hosters restrictions. Most of the time they already have the file cached on their server so the download speed it's max out at your ISP limit.
> [!NOTE]  
> Real Debrid is a paid service
Supported domains include `mega.nz`, `rapidgator`, `google drive`, `1fichier`, `k2s`, etc. List of all supported domains can be found here (250+): https://api.real-debrid.com/rest/1.0/hosts/domains
Implementation is fully …

feat: add integration of Real Debrid

---

.github/workflows/ruff.yaml
.pre-commit-config.yaml
CONTRIBUTING.md
poetry.lock
pyproject.toml

This PR is a proposal to integrate [ruff ](https://github.com/astral-sh/ruff) as a linter and auto formatter for the entire repo, to minimize `git diff` on new commits, use a standard style and remove the necessity for future PRs that are just reformats
> [!CAUTION]
> This PR will highlight a ***bunch of issues*** in the entire codebase and will prevent any new commits from being made until those issues are fixed. It will also ***break basically every branch*** after the issues are fixed cause it will be practically impossible to rebase from master. They will require a manual (***huge***) merge conflict resolution. However, it will only need to be done once and `ruff` will handle any new commits in the future.
I will create a new PR with all the necessary fixes after this PR is merged. …

ci: add ruff as linter and formatter + pre-commit hooks

---

cyberdrop_dl/clients/errors.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/utils/dataclasses/url_objects.py

1. `MediaItem` objects are now created passing the original `ScrapeItem` as a parameter
2. Add `parents` property to `MediaItem`
This fixes an issue where `Download_Errors` logs were missing the `origin` value after the ruff refactor

fix: log origin of download errors

---

.github/workflows/codeql-analysis.yml
.github/workflows/create_release.yaml
.github/workflows/publish-to-pypi.yaml
.github/workflows/ruff.yaml

1. Update version of deprecated actions
2. Create sub-folder inside zip for GH releases action
3. Remove `changed-files: "true"` from ruff action now that the entire repo passes the check

ci: update actions

---

cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
cyberdrop_dl/scraper/crawlers/fapello_crawler.py
cyberdrop_dl/scraper/crawlers/kemono_crawler.py
cyberdrop_dl/scraper/crawlers/leakedmodels_crawler.py
cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
cyberdrop_dl/scraper/crawlers/pixeldrain_crawler.py
cyberdrop_dl/scraper/crawlers/reddit_crawler.py
cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
cyberdrop_dl/scraper/crawlers/xbunker_crawler.py

Do not use await when calling `crawler.handle_external_link()`
Fixes #255

fix: external links call from crawlers

---

cyberdrop_dl/main.py

Move main `rich.live` to `runtime` to prevent overlapping with the `rich.live` instances of `post_runtime` (hashing and sorting)

fix: multiple running rich.live loops

---

cyberdrop_dl/managers/log_manager.py
cyberdrop_dl/managers/path_manager.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
cyberdrop_dl/scraper/crawlers/leakedmodels_crawler.py
cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
cyberdrop_dl/scraper/crawlers/xbunker_crawler.py

Same changes as #166 except it does not include any of the UI prompts to import cookies. 
User have to manually create the cookies file inside `AppData / Cookies`. I will add the prompt on a later PR with the rework of all the prompts.
Related to #250

feat: import cookies from file (any supported site)

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/managers/client_manager.py
cyberdrop_dl/managers/manager.py

1. Handle cases where flaresolverr returns the same DDosGuard page
2. Use a flaresolverr session to keep cookies alive
3. Allow the user to input a full scheme URL as the flaresolverr config option
4. Redefine all flaresolverr functions as methods of their own class, `Flaresolverr`
The flaresolverr session is a global session for all crawlers cause creating a session for each one would take too many resources on the host PC. This _may_ cause issues with headers. The request headers come from each crawler client session which are added to the base request headers but never removed. There's a chance the request may be sent with incorrect headers but i'm not 100% sure.
Marking as a draft for now while testing
Resolves #172 
Resolves #258 
~~Related to #250~~ 
Update: 
Added cookies from …

refactor: better flaresolverr integration

---

cyberdrop_dl/scraper/crawlers/celebforum_crawler.py
cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
cyberdrop_dl/scraper/crawlers/simpcity_crawler.py
cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
cyberdrop_dl/scraper/crawlers/xbunker_crawler.py

This merges
https://github.com/jbsparrow/CyberDropDownloader/pull/272
Into  master

Merge Fixes for crawler into master

---

cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/utils/utilities.py

1. Only log `Download finished` if the download was successful
2. Tried to do the same for the `Scrape finished` log message but this will require modifying every crawler to make them return if the scrape was successful or not. Instead, I just removed the log entirely and changed `Scrape starting: <URL>` to `Scraping <URL>`
3. Any error while scraping/downloading would still be logged
Resolves #259

refactor: only log "download finished" if the download was successful

---

pyproject.toml

The previous syntax for specifying  jeepney was not compatible with pip

Fix: Syntax error fix for jeepney

---

cyberdrop_dl/managers/args_manager.py
cyberdrop_dl/managers/config_manager.py
cyberdrop_dl/utils/args/args.py

1. fix `--log-folder` not overriding config value
2. fix `bool` values being replaced by numbers in the config

fix: config settings errors

---

cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
cyberdrop_dl/ui/prompts/user_prompts.py

img.wiki uses `/images` subpath to serve their assets (direct links). Matching by host is not enough, regex needs to match the entire URL
fixes #298

fix: chevereto CDN regex

---

cyberdrop_dl/utils/utilities.py

1. Fallback to `$EDITOR`  when running without DE or over SSH (linux)
2. Fallback to `micro` if `$EDITOR` is not set
3. Fallback to `nano` if micro is not installed
4. Fallback to `vim` if nano is not installed
5. Throw `No default text editor found` error if every check fails
Fixes #307

fix: open config files when running without DE (linux)

---

CHANGELOG.md
README.md
docs/reference/configuration-options/authentication.md
docs/reference/configuration-options/global-settings.md
docs/reference/configuration-options/settings.md
docs/reference/supported-websites.md
pyproject.toml

1. Update wiki entries and changelog to release current master as 5.7.2
2. Remove `xxhash` from dependencies to pospone merging #299 until the next release

docs: wiki and changelog updates for 5.7.2 release

---

cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
cyberdrop_dl/scraper/crawlers/reddit_crawler.py
cyberdrop_dl/scraper/scraper.py

1. Move all crawler imports to `crawler.py` so they can be used in `scraper.py` without individual domain mappings
2. Add proper integration of crawlers that support multiple sites/domains. A multi-site crawler must define a `SUPPORTED_SITES` dict as a property, where each key is a site and each value is a list of domains associated with that site. ex: `{"reddit": ["reddit", "redd.it"]}`. `SUPPORTED_SITES` only needs to be declared is the crawler actually supports multiple domains. Single site crawlers do not need to be modified.
3. Add `SUPPORTED_SITES` property to `reddit`, `bunkr` and `chevereto` crawlers
4. Only startup crawlers if they are actually going to be used in the current run
5. In cases where there are multiple supported domain matches for an URL (ex: `xbunker`, …

refactor: add proper integration of crawlers that support multiple sites/domains

---

cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py

1. Update CDN definitions logic + add new `soup` cdn
2. Parse custom name for files. Bunkr now uses a random uuid for every file as its filename. We can get the actual file name from the soup or from the query parameter `n` on direct links (CDNs)
3. Remove bunkr from domains to apply `remove_file_id` on
merging onto `coomer-patch` to include this patch in the v5.7.3 release

fix: update bunkr crawler to handle uuid filenames

---

poetry.lock
pyproject.toml
scripts/release/start_linux.sh
scripts/release/start_macOS.command
scripts/release/start_windows.bat

`aiolimiter` released v1.1.1 today (2024-11-30), which breaks some functionality of CDL.
This is a temporary workaround, pining the version to v1.1.0. We need to update the actual code at some point to properly use v1.1.1

chore: pin aiolimiter to v1.1.0

---

cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/managers/client_manager.py

The same `MediaItem` URL can be downloaded multiple times if `--ignore-history` is used
Duplicate `ScrapeItem` URLs are still skipped, to prevent loops.
- Fixes #337

fix: allow duplicate files download on the same run with --ignore-history

---

cyberdrop_dl/config_definitions/custom_types.py
cyberdrop_dl/utils/transfer/db_setup.py
cyberdrop_dl/utils/transfer/transfer_v4_config.py

Config is immediately validated after import, but given that most of the v4 options were `str` or `bool` (except for `proxy`) importing from v4 is actually easier that importing from v5
I had to replace `SupportedSites` Enum with a list. It was giving me validation errors because the enum names and their values are different. Even when the validation was successful, I was getting a bunch of warnings from pydantic. We need to switch back to using regular lists for those. I will make new PR for that

fix: v4 import to pydantic config

---

cyberdrop_dl/config_definitions/config_settings.py
cyberdrop_dl/main.py
cyberdrop_dl/managers/log_manager.py
cyberdrop_dl/managers/path_manager.py
cyberdrop_dl/ui/progress/sort_progress.py
cyberdrop_dl/utils/args.py
cyberdrop_dl/utils/sorting.py

1. Always resolve paths before sorting
2. Allow inplace sorting by saving the list of all files to sort before doing anything. This allows for `scan_dir` and `download_dir` to be the same
3. Refactor and simplify sorting logic
4. Allow selective sorting: skip sorting a type of file by setting the format to `null`

fix: sorting

---

cyberdrop_dl/ui/program_ui.py
cyberdrop_dl/ui/prompts/user_prompts.py
cyberdrop_dl/utils/cookie_management.py

- Fix syntax error while logging failed cookie imports
- Only override config sites of the same type as the user selected on the UI (FORUMS or WEBSITES)

fix: cookie import error log

---

cyberdrop_dl/ui/prompts/basic_prompts.py
cyberdrop_dl/ui/prompts/user_prompts.py
cyberdrop_dl/utils/utilities.py

Switched the domain selection prompt to use fuzzy choices with checkbox styles to allow the user to search for websites.
Also rearranged fuzzy search arguments to match other prompts from `basic_prompts.py` (choices before message) and added the ability to use a custom validator for fuzzy search.

Switch domain selection to fuzzy choices

---

cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py

Override CDN is necessary. This is just a workaround to use their new servers without having to make a new request.

fix: override cdn on albums (bunkr)

---

cyberdrop_dl/scraper/crawlers/coomer_crawler.py
cyberdrop_dl/scraper/crawlers/kemono_crawler.py
cyberdrop_dl/scraper/crawlers/nekohouse_crawler.py

Skip sending them back to the scrape queue. Applies to Coomer, Kemono and Nekohouse

refactor: send media files straight to downloader

---

.github/workflows/create_release.yaml
.pre-commit-config.yaml

1. Fix some parsing issues on GH release action
2. Extract the content for the release from `CHANGELOG.md` [^1] [^2] [^3]
3. Update ruff pre-commit hook to v0.8.4
[^1]: The logic is not robust. If `CHANGELOG.md` is incorrectly formatted, it will fail. 
[^2]: If `CHANGELOG.md` does not have an entry for the same tag as the input tag for the workflow, it will fail. This is intentional
[^3]: Workflow is still manually triggered. This is intentional

ci/cd: update GH release workflow + ruff pre-commit hook

---

cyberdrop_dl/config_definitions/config_settings.py
cyberdrop_dl/utils/logger.py
docs/reference/configuration-options/settings/runtime_options.md

- Allow only `NonNegativeInt`
- Only print to console manually if `console_log_level` is disabled (above 50)
- Add wiki entries for log levels
- Resolves #396

refactor: update log settings

---

cyberdrop_dl/main.py
cyberdrop_dl/utils/logger.py

Use custom `Console` object to redact any string before writing to the log file, including traceback logs

refactor: redact traceback logs

---

CHANGELOG.md
cyberdrop_dl/utils/args.py

This was already replaced with `--download-folder` but was missing the deprecated entry

refactor: add `--output-folder` to deprecated args

---

cyberdrop_dl/config_definitions/config_settings.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/coomer_crawler.py
cyberdrop_dl/scraper/crawlers/kemono_crawler.py
cyberdrop_dl/scraper/crawlers/nekohouse_crawler.py
cyberdrop_dl/scraper/crawlers/reddit_crawler.py
cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
docs/reference/cli-arguments.md
docs/reference/configuration-options/settings/download_options.md

Allow defining a custom format for the name of the folder created when using `--separate-posts`
| Type           | Default  |
|----------------|----------|
| `NonEmptyStr`  | `{default}`|
Unique Path Flags:
> `date`: date of the post
>
> `number`: post number
>
> `id`: same as `number`
>
> `title`: post title
Setting it to `{default}` will use the default format, which is different for each crawler:
| Site          | Default Format |
|----------------|----------|
| `Coomer`, `Kemono` and `Nekohouse` | `{date} - {title}`|
| `Forums` | `post-{number}`|
| `Reddit` | `{title}`|

feat: add `--separate-posts-format`

---

.gitignore
cyberdrop_dl/config_definitions/config_settings.py
cyberdrop_dl/config_definitions/custom_types.py
cyberdrop_dl/main.py
cyberdrop_dl/managers/config_manager.py
cyberdrop_dl/utils/apprise.py
cyberdrop_dl/utils/args.py
cyberdrop_dl/utils/constants.py
cyberdrop_dl/utils/logger.py
cyberdrop_dl/utils/utilities.py
cyberdrop_dl/utils/yaml.py
docs/reference/notifications.md
poetry.lock
pyproject.toml
tests/fake_classes/managers.py
tests/test_apprise.py
tests/test_files/apprise/invalid_multiple_urls.txt
tests/test_files/apprise/invalid_single_url.txt
tests/test_files/apprise/valid_multiple_urls.txt
tests/test_files/apprise/valid_single_url.txt

- Do not convert to `yarl.URL`, to keep the validation of the model as simple as possible
- Handle simplified cases for URLs that have specific limitations. ex: OS notifications have a character limit
- Move Apprise utils to its own module
- Capture log messages of every apprise notification attempt. Messages will only be logged if the notification failed
- Capture log messages of the regular webhook notification. Messages will only be logged if the notification failed
- Add `pywin32` as conditional dependency for Windows (required for Windows native notifications)
- Enable native notifications by default on Windows. User can disable them removing the line from the `Apprise.txt` file, or deleting the entire file
- Fixes #405 
This is what the Windows notification looks like:
---
I did not …

fix: `AppriseURL` parsing

---

.github/workflows/ruff.yaml
.pre-commit-config.yaml
pyproject.toml

- `toml-sort`
- `check-merge-conflict`
- `name-tests-test`
- `check-illegal-windows-names`
- `check-case-conflict`
- `check-executables-have-shebangs`
- `check-shebang-scripts-are-executable`
- `check-added-large-files`
- `ASYNC` # `async` calls that do not `await` anything or use blocking methods ([link](https://docs.astral.sh/ruff/rules/#flake8-async-async))
- `FA102`  # future annotations ([link](https://docs.astral.sh/ruff/rules/future-required-type-annotation/))
- `PTH`  # use `pathlib` instead of `os` ([link](https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth))
- `T20`  # flake8-print ([link](https://docs.astral.sh/ruff/rules/#flake8-print-t20))
- `TID`  # flake8-tidy-imports ([link](https://docs.astral.sh/ruff/rules/#flake8-tidy-imports-tid))
- Replace `TCH` with `TC` (new …

ci/cd: update workflows, ruff rules and pre-commit hooks

---

CHANGELOG.md
README.md
docs/reference/cli-arguments.md
docs/transition-to-v6.md
pyproject.toml

- ~~Assumes #407 will be merged before release~~ Postponed for the next release
- Assumes #422 will be merged before release

docs: wiki and changelog updates for v6.1.0 release

---

cyberdrop_dl/scraper/crawler.py

This PR removes the async lock from the crawlers and replaces it with a semaphore with a capacity of 20
In reality, neither the lock nor the semaphore are needed. The requests are actually limited by the `request_limiter` of each crawler, not the lock. However, i could not remove the lock because it will brake the logic for the UI scrape queue, that's why i replaced it with a semaphore instead.
The lock was making each crawler behave synchronously and the `request_limiter` was never close to being reached. This was only for the crawlers. The downloaders have a semaphore already with a different capacity per domain, so they were not affected. The default capacity for each downloader is 3, defined by `--max-simultaneous-downloads-per-domain`
- The main drawback of replacing the lock with a …

perf: remove crawler scrape lock

---

cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/utils/transfer/transfer_hash_db.py

Add a new debug var for SimpCity support. Allowing us to enable SimpCity support without running in IDE or on a development build.

New debug var

---

cyberdrop_dl/clients/errors.py
cyberdrop_dl/managers/client_manager.py
cyberdrop_dl/managers/real_debrid/api.py
cyberdrop_dl/managers/real_debrid/errors.py
cyberdrop_dl/managers/realdebrid_manager.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
cyberdrop_dl/scraper/crawlers/chevereto_crawler.py
cyberdrop_dl/scraper/crawlers/cyberdrop_crawler.py
cyberdrop_dl/scraper/crawlers/gofile_crawler.py
cyberdrop_dl/scraper/crawlers/imgbox_crawler.py
cyberdrop_dl/scraper/crawlers/imgur_crawler.py
cyberdrop_dl/scraper/crawlers/mediafire_crawler.py
cyberdrop_dl/scraper/crawlers/omegascans_crawler.py
cyberdrop_dl/scraper/crawlers/reddit_crawler.py
cyberdrop_dl/scraper/crawlers/saint_crawler.py
cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
cyberdrop_dl/scraper/crawlers/xxxbunker_crawler.py
cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/utils/constants.py
cyberdrop_dl/utils/utilities.py
cyberdrop_dl/utils/yaml.py

- Use dataclasses for posts (reddit)
- Pass `scrape_item` as origin for `web_pager` to log them with errors (if any) (chevereto) 
- Fix "Loose Files" folder not being created (all crawlers)
- Add custom `MediaFireError` (mediafire)
- Use the correct HTTP error codes for `ScrapeError`. Do not overload `403` or `404` unless that's the actual response. Use `422` for errors found while parsing the HTML
- Make `RealDebridError` inherit from `CDLBaseError`
- Move all custom errors to `clients.errors`. However, this needs to be moved (to it own module maybe?) cause not all errors are from clients (ex: YAML errors)
- Should fix #426

fix: general crawler fixes

---

cyberdrop_dl/clients/hash_client.py

- keep reference to hashed files (`HASHING.INPLACE`) to not hash them again at the end
- use sets when possible

perf: improve hashing

---

cyberdrop_dl/scraper/crawlers/chevereto_crawler.py

Parse the ID of the URLs to create the canonical URL to use for database lookups. This is to make sure matches are always found even if the album/image name changed or a canonical URL was already used as input

refactor: use canonical URLs (chevereto)

---

cyberdrop_dl/scraper/crawlers/pixeldrain_crawler.py

- This is a workaround to handle shared filesystem links cause their ID are not reachable from the public API yet 
- Only videos and images are supported

feat: add support for filesystem URLs (pixeldrain)

---

cyberdrop_dl/scraper/crawlers/saint_crawler.py

- As far as i can tell, these URLs always require cookies cause they trigger a DDoS Guard challenge
- Resolves #458 
There's a regression from a few PRs back. CDL no longer triggers `DDoS-Guard` errors, only `403 forbidden`. I will fix it on another PR

feat: add support indirect links (routed via api) (saint)

---

docs/getting-started/README.md
docs/getting-started/cyberdrop-dl-install.md
scripts/release/start_linux.sh
scripts/release/start_macOS.command
scripts/release/start_windows.bat

Update all start scripts to add a `--help` / `-h` option, `--no-update`, to skip auto-updating Cyberdrop-DL, and config options to enable/disable auto-updating Cyberdrop-DL and pip. These new config options are enabled by default.
Also added a check to determine whether or not Cyberdrop-DL is already installed.

Update start scripts

---

cyberdrop_dl/scraper/crawlers/chevereto_crawler.py

fixes 503s while scraping
I will make a different PR with some refactors to automatically use the `rate_limit` of the crawler without having to manually use a context manager
The change is small but it needs to be added to every crawler

fix: update jpg5 rate limit

---

cyberdrop_dl/clients/hash_client.py
cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/main.py
cyberdrop_dl/managers/live_manager.py
cyberdrop_dl/managers/progress_manager.py
cyberdrop_dl/ui/progress/deque_progress.py
cyberdrop_dl/ui/progress/file_progress.py
cyberdrop_dl/ui/progress/hash_progress.py
cyberdrop_dl/ui/progress/scraping_progress.py
cyberdrop_dl/ui/progress/sort_progress.py
cyberdrop_dl/utils/sorting.py

- Use deque to speed up the time it takes to redraw the entire UI. Helps reduce flickering on some terminals
- Use a base class for file, scrape and sort progress, to reduce code duplication

perf: use deque for file, scrape and sort progress

---

cyberdrop_dl/managers/cache_manager.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/ui/program_ui.py

Add the last version that CDL was run on to the cache. This would aid in detecting when a transition is necessary or when to tell a user that they must downgrade in order to transition.

Add last version run with to the cache

---

cyberdrop_dl/managers/manager.py
docs/reference/configuration-options/settings/ignore_options.md

Fix regression introduced from pydantic config validation. `skip-hosts` and `only-hosts` values passed from CLI should be added to the config values, not overridden

fix: regression - additive config options

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/downloader/downloader.py

Allows retrying them with `--retry-failed`, for any error (Insufficient space error, skipped by config or just not processed)
Only downside if that they will be added with `null` as `filesize` cause the initial request to get the file info has not been made yet. I'm not sure if something will break without it. Could not find a function that needs it except for the UI

refactor: add `MediaItem` inmediatly to db 

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/allporncomix_crawler.py
cyberdrop_dl/scraper/crawlers/bellazon_crawler.py
cyberdrop_dl/scraper/crawlers/coomer_crawler.py
cyberdrop_dl/scraper/crawlers/f95zone_crawler.py
cyberdrop_dl/scraper/crawlers/gofile_crawler.py
cyberdrop_dl/scraper/crawlers/imagebam_crawler.py
cyberdrop_dl/scraper/crawlers/imgur_crawler.py
cyberdrop_dl/scraper/crawlers/nudostar_crawler.py
cyberdrop_dl/scraper/crawlers/realbooru_crawler.py
cyberdrop_dl/scraper/crawlers/rule34xxx_crawler.py
cyberdrop_dl/scraper/crawlers/socialmediagirls_crawler.py
cyberdrop_dl/scraper/crawlers/titsintops_crawler.py
cyberdrop_dl/scraper/crawlers/tokyomotion_crawler.py
cyberdrop_dl/scraper/crawlers/xbunker_crawler.py
cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
cyberdrop_dl/scraper/crawlers/xxxbunker_crawler.py
cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/utils/data_enums_classes/url_objects.py

- Fix `write_last_forum_post`
- Fix nudostar base domain
- Add support for redirect URLs
- Add more conditions to `is_attachment` check
- Raise `ValueError` if an URL path is unsupported instead of manually logging it. This can be applied to all crawlers
- Handle `ValueError` inside `create_task_id`
- Assert that no 2 crawlers have mappings to the same domain
- Simplify `forum_login` and move it from the base crawler to the Xenforo crawler
- Send posts to the queue instead of awaiting them
- Refactor some methods of the crawler
- Fixes invalid `parse_url` usage on some other crawlers
- Related to #516 
- Fixes #519 
- Fixes #524 
It may actually fix 516 but i don't have an account to test it

fix: xenforo crawlers

---

cyberdrop_dl/managers/progress_manager.py
cyberdrop_dl/ui/progress/deque_progress.py
cyberdrop_dl/ui/progress/downloads_progress.py
cyberdrop_dl/ui/progress/hash_progress.py
cyberdrop_dl/ui/progress/statistic_progress.py

Wait for a new release before merging this
***
- Create a base `StatsProgress` class for both download and scrape failures, to reduce code duplication
- Prettify failures by splitting them and capitalizing them if necessary (ex: `ClientConnectorError` - > `Client Connector Error`)
- Change the way some stats are printed
- Use thousand separator for number in stats
- Resolves #476

refactor: create base class for download and scrape failures + reformat stats

---

cyberdrop_dl/managers/db_manager.py
cyberdrop_dl/utils/database/tables/history_table.py

Previously downloaded media files will never be updated so it better to just delete them
- Related to #522

fix: delete invalid database rows on startup

---

cyberdrop_dl/scraper/crawlers/xenforo_crawler.py

- Supersedes and closes #541 
- Check if the link is an attachment before checking the link host
- Make `handle_internal_link` take an `ScrapeItem` instead of a `link` + `scrape_item`
- Use `error_handling_wrapper` for `handle_internal_link`

fix: attachments downloads + `NoExtensionError` handling (xenforo)

---

cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/cyberfile_crawler.py
cyberdrop_dl/scraper/crawlers/pixhost_crawler.py
cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/utils/database/tables/history_table.py

I notice this with `--retry-failed`. Some URLs were being marked as previously downloaded immediately, even though they were supposed to have failed
The URLs were duplicated in the database. 1 as `no_crawler` and 1 for the actual crawler.
I only enabled this for Iceyfile and PixHost. I may have missed another crawler that may also need to be updated

fix: delete old rows of previously unsupported URLs

---

CHANGELOG.md
cyberdrop_dl/clients/download_client.py
cyberdrop_dl/clients/errors.py
cyberdrop_dl/config_definitions/config_settings.py
cyberdrop_dl/main.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py
cyberdrop_dl/scraper/crawlers/gofile_crawler.py
cyberdrop_dl/utils/constants.py
cyberdrop_dl/utils/data_enums_classes/url_objects.py
cyberdrop_dl/utils/utilities.py
docs/reference/configuration-options/settings/ignore_options.md

- Split util functions into single responsibility functions
- Use `pathlib.Path` instead of bare strings when possible
- Allow downloading files with no extension
- Resolves #200 
This feature works by just assuming any file without an extension is an `.mp4` file. That means any option that applies to videos like `--exclude-videos` and `--minimum-video-size` will apply to them
The actual file will be downloaded without an extension cause the filename always comes from the`MediaItem.filename` property but the config checks are done with the `MediaItem.ext` property. We are just manually setting `MediaItem.ext` to `.mp4`
There will be a config setting to enable this but it will do nothing by the default. Its needs to be implemented on a per crawler basis by calling `get_filename_and_ext` …

feat: allow downloads of files with no extension

---

cyberdrop_dl/scraper/crawlers/pixhost_crawler.py
cyberdrop_dl/utils/database/tables/history_table.py

- Use canonical URL to make sure the referer is always the same (pixhost)
- Handle any kind of cdn as input: thumbs or images (pixhost)
- Never download thumbnails, always download the full res image, even if the input URL is a thumb (pixhost)
- Change `update_unsupported` to also update all possible subdomains in the database (all crawlers)

fix: duplicated entries (pixhost)

---

cyberdrop_dl/scraper/crawler.py

- Fixes random `NoFileExtension` errors

fix: extension being assigned to duration (`MediaItem`)

---

cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py

The refactor fallback_filename from h1 bypasses `utils.sanitize_filename` codepath (which I can't see used directly so running through `get_filename_and_ext`)
fixes 3ff244e630cd39881b1aa96f6b88e4941f55351a

fix: bunkr missed sanitize_filename

---

cyberdrop_dl/clients/errors.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
cyberdrop_dl/utils/utilities.py

The scrape progress for crawlers that handle multiple items within the same method (like albums) may still fail. If a single invalid URL is found, the entire album scrape process will stop. but at least CDL will not crash.
Realistically, this would never happen. It will only happen inside forums crawlers because CDL has to process raw input from their users.
- Fixes #561
- Fixes #638
- Resolves #640

fix: handle invalid urls

---

cyberdrop_dl/clients/errors.py
cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/managers/log_manager.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/xenforo_crawler.py
cyberdrop_dl/utils/utilities.py

- Add referer column to download errors csv
- Add referer info to messages in the main log file
- Simplify handling of download errors
- See: https://github.com/jbsparrow/CyberDropDownloader/pull/631#issuecomment-2662689692
- Needs #641

refactor: add `referer` info to download errors logs

---

cyberdrop_dl/downloader/downloader.py

Ideally, the crawlers themself should identify these URLs and raise an `ScrapeError` instead of sending them to the downloader.
This is just a fail safe

fix: do not download known invalid files

---

cyberdrop_dl/utils/database/tables/history_table.py

fixes a bug where download filename is overwritten as a empty value 
before the filename check can check the existence of the previous download_filename
leading to the previous file never resuming as iterate_filename is called

fix: don't update download_filename unless the value is not empty

---

cyberdrop_dl/clients/errors.py
cyberdrop_dl/main.py
cyberdrop_dl/utils/logger.py

This was pointed out by @datawhores in #345. I was checking the linked issue in rich and someone proposed their own custom class to not pad the log lines. See: https://github.com/Textualize/rich/discussions/344#discussioncomment-11788991
I modified it to only remove the right padding.
- Do not pad the logs to the right
- Do not show the file path if it is `logger.py:...`
- The file path (if any) will show up right next to the log level
The main reason for using a rich logger is for the rich tracebacks, so i tested those as well and they look fine:

refactor: remove left padding from log files

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/managers/client_manager.py

Sometimes flaresolverr successfully solves a challenge but does not send a response, just cookies.
If that happens, we have skip trying to make a soup from the response and just re-make the original request with the new cookies.
Related to #635

fix: handle empty responses from flaresolverr

---

cyberdrop_dl/scraper/crawlers/hotpic_crawler.py

- Add support for direct URLs as input
- Always download full res images instead of thumbnails
- Add support for their alternative domain, 2385290.xyz
- Add support for videos
- Use canonical URL for database

feat: improve hotpic crawler

---

cyberdrop_dl/managers/client_manager.py

- Use a lock to ensure we only create a single flaresolverr session
- Use a lock to ensure we make 1 request at a time to flaresolverr
Related to #635

fix: use async locks for flaresolverr 

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/managers/client_manager.py

Also moved the check downstream to only throw this error if the response was successful
- Resolves #692

refactor: report downloads with no content type as `InvalidContentType`

---

cyberdrop_dl/main.py
cyberdrop_dl/ui/program_ui.py
cyberdrop_dl/utils/check_updates.py
cyberdrop_dl/utils/constants.py
cyberdrop_dl/utils/updates.py
cyberdrop_dl/utils/utilities.py

- Ignore any error that may raise while checking for updates
- Move update utils and constants to its own module
- Show update messages with color when running `check updates` from the main UI
- Use stdlib `packaging.version` instead of regex to parse versions
- Refactor all the functions
- Fixes #667
When running a prerelease version:
- Show a warning if a newer prerelease version of the same kind is available (this was the current behavior)
- Show a warning if a newer prerelease version is available but from a different kind
- Show a warning if the latest stable version is newer that the current prerelease version

fix: handle errors while checking for updates

---

cyberdrop_dl/main.py
cyberdrop_dl/utils/constants.py

Changes the startup logger behavior by creating and immediately destroying all of its handlers.
It will create the startup logger before any critical section of code where we may not have the manager ready.
It will destroy the startup logger after each of these sections but only delete the startup log file if the file is empty.
These sections are:
- The setup of the manager itself
- Calls to `manager.config_manager.change_config`
Also refactors some of the logic for the main and debug loggers

fix: `File is being used by another process` error if a validation error raises when running multiple configs

---

cyberdrop_dl/env.py
cyberdrop_dl/main.py
cyberdrop_dl/profiling.py
cyberdrop_dl/scraper/__init__.py

- Rename some env variables
- Check that the value of `CDL_DEBUG_LOG_FOLDER` exists, is a folder and CDL has permissions to write to it (if supplied)
- Check that CDL has permissions to write to the main log file
- An error on any of the previous cases will be logged to the startup log file

fix: handle OS errors on startup (log files)

---

cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py

- Use the new API to get the file URL from get.bunkr.su
- Now 1 to 3 requests per item in an album are needed.
- Use the new scrape item syntax
- Remove functions and methods no longer in use
- Needs #712 for the new scrape item syntax

fix: use new api to get file (bunkr)

---

cyberdrop_dl/managers/progress_manager.py
cyberdrop_dl/scraper/scraper.py
cyberdrop_dl/utils/logger.py

Added hyperlinks to paths that are logged to the terminal. If the user's terminal supports it, the path will be embedded as a hyperlink and the user can click on it to open the file/folder.
Also added the log folder to the end of run output because many people have trouble finding it.
Also hides the 'Input File' and 'Input URL Groups' runtime stats if the user isn't using the input file. Closes #718

Feature: Add Hyperlinks to Logged Paths

---

cyberdrop_dl/managers/client_manager.py
cyberdrop_dl/managers/progress_manager.py
cyberdrop_dl/scraper/scraper.py

I made it an async function even though it does not need to be, just to make it easier to concat with other async context managers. 
The function intentionally has no lock. The status messages will overwrite each other if used improperly.
- Related to #687 
- Needs #688

feat: show status messages at the bottom of the UI

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/clients/hash_client.py
cyberdrop_dl/config_definitions/config_settings.py
cyberdrop_dl/main.py
cyberdrop_dl/utils/data_enums_classes/url_objects.py
cyberdrop_dl/utils/dumper.py

- Save `downloaded` and `hash` as properties of `MediaItem`
- Add `--dump-json` option to create a jsonl file with the info of all the items processed in this run *
Not all items are saved because we do not keep a reference for the skipped ones. Keeping track of them will require a bigger refactor but i will wait until #557 is merged to do it
I added the option to the `Files` category and not `Logs` because the results are not "logged". The file is only created at the end of a run, inside `post_runtime`. If CDL crashes or is stopped by the user, the file will not be created

feat: add `--dump-json` option

---

cyberdrop_dl/managers/client_manager.py

flaresolverr locks program currently because recursive calls to the _requests function means the child call is stuck waiting for the parent to release

fix: remove recursive requests calls and recursive locks from flaresolverr class

---

cyberdrop_dl/clients/errors.py
cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/managers/log_manager.py
cyberdrop_dl/utils/utilities.py

- Handle error formatting inside CDL custom error
- Create a custom class to hold the 3 possible messages when an error raises (UI, main log and CSV log messages)
- Do not retry `InvalidContentType` errors

refactor: simplify error message logging

---

cyberdrop_dl/clients/download_client.py

They don't return any content type. This may be happening with other sites

fix: do not check content type in headers

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawlers/google_drive_crawler.py

- Add support for files and folders from google drive, google docs, sheets and slides
- Does not require auth and does not use the API. It will only work with public links unless cookies are used
- Most of the logic is from [gdown](https://github.com/wkentaro/gdown). They essentially reversed engineered how google creates the requests and how to get the required parameters for it
- This implementation can download folders with any number of files (`gdown` only supports folders with up to 50 files)
Current state is fully working but I had to change some core functionality from unrelated modules to get this to work. I will split this into multiple PRs and clean up the code.
The main difference is that we need both the soup and the headers to get all required info. But right now `get_soup` …

feat: add google drive support

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawlers/dropbox_crawler.py
cyberdrop_dl/utils/args.py

- Add support to download files and folders from dropbox.
- Downloading folders requires the user to supply a dropbox token to CDL *
- Needs #669 
We can actually download folders without an API token but they will download as a single zip file. I have implemented the logic to do it but it's hardcoded with a variable as disabled because i think it will be unexpected behavior for most users. I may add a CLI only option to toggle this, similar to the tiktok audios option
It does not actually need #669 but the code for parsing the headers is the same. I would like to refactor that code as a module and use it for both crawlers

feat: add dropbox support

---

.github/workflows/ci.yml
cyberdrop_dl/main.py
cyberdrop_dl/profiling.py
cyberdrop_dl/utils/args.py
poetry.lock
pyproject.toml
tests/test_cli.py
tox.ini

- Add a GH workflow to run CDL on pushes to master with ubuntu, windows and macOS, python 3.11 to 3.13
- Add tox config to be able to replicate the behavior of the action locally
- Add a basic test to just run `--help`
@jbsparrow you have to set a secret on the repo for the Apprise tests to work. The name should be `APPRISE_TEST_EMAIL_URL`
Its values does not have to be an email, it can be anything that supports attachments, like a discord webhook, but it should be in the apprise format

ci/cd: run tests with matrix in ci

---

CHANGELOG.md
cyberdrop_dl/utils/sorting.py
cyberdrop_dl/utils/utilities.py

This speeds up checking for and removing partial and empty files/folders by up to 2 times.
In my testing, checking partials took an average of 54.4 seconds before these changes, and an average of 32.8 seconds after these changes. Both were averaged over five tests.
Sorting is also faster now but I didn't do tests for the speed increase. I estimate around a 1.2-1.5x speed increase.

Increase Partial File Removal Speed

---

.github/workflows/ci.yml
cyberdrop_dl/utils/apprise.py
tests/test_apprise.py

- Do not tests apprise notifications on every python version. They will only be tested once on their own runner using Ubuntu and python 3.11
- Fix relative path of apprise tests file in CI
- Update expected log messages for using discord instead of an email
- Include the name of the tests in the notifications
- Do not run apprise tests in verbose mode. The webhook URL was being logged. I'm not sure if this is enough to prevent that.
The apprise log messages for discord do not include if an attachment was successful or not, so i had to also refactor the apprise module itself to:
- Include failed attachment in logs (the log message comes from CDL, not apprise)
- Exit on apprise validation errors

ci/cd: update tests

---

cyberdrop_dl/main.py
cyberdrop_dl/utils/dumper.py

- Allow writing not ascii characters when using `--dump-json`)
- Remove async definition for dumper (there are no other tasks going on while CDL creates this file, and no UI)

refactor: allow writing not ascii chars (`--dump-json`)

---

cyberdrop_dl/scraper/scraper.py

Process URLs as soon as the come. Do not wait for all of them to be parsed. This is specially useful when using retry options.
Drawback: We only know the total URL count at the end of the run

perf: use generators for input item URLs

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/managers/cache_manager.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/scraper/crawlers/reddit_crawler.py
cyberdrop_dl/scraper/filters.py
cyberdrop_dl/utils/args.py
cyberdrop_dl/utils/constants.py
docs/reference/cli-arguments.md

https://github.com/jbsparrow/CyberDropDownloader/issues/544
This add an option to disable the main file cache for the current  run, by using a throwaway in memory cache
The cache would be erased after the current run, and setting the expired_after value to zero means no value will be saved to the cache
Orginally I wanted to change the cache_control_manager function, but it doesn't have access to the manager class

feat: disable cache 

---

cyberdrop_dl/utils/dumper.py

The actual error comes from some crawler that is saving the date as a string instead of a timestamp. This just prevent CDL from crashing
- Fixes #774

fix: jsonl timestamp serializer

---

cyberdrop_dl/ui/program_ui.py
cyberdrop_dl/utils/utilities.py

- Use `shutil.which` to find available text editor
- Show keyboard bindings footer when using `micro`
- Halt CDL until text editor process finishes
- Revalidate and reload config after the user edits any config file from the UI
- Use `$EDITOR` value (if available) on Windows and macOS

refactor: revalidate config after the user edits it from the UI

---

cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py

Add the `n` to the download URL if it is missing.
The full URL (with the `n` parameter) seems to be cached, but not the bare URL

fix: slows downloads (bunkr)(2)

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/managers/client_manager.py
cyberdrop_dl/scraper/crawlers/spankbang_crawler.py
cyberdrop_dl/utils/javascript.py
poetry.lock
pyproject.toml

See https://github.com/jbsparrow/CyberDropDownloader/issues/700#issuecomment-2678442030 for details
- Define a new method `get_soup_cffi` that uses `curl_cffi` instead of `aiohttp` to impersonate a browser. It will impersonate chrome by default
- Use `get_soup_cffi` in spankbang crawler
- Handle deleted videos (spankbang)
- fix json from javascript parsing (do not use regex by default)
- Response from `get_soup_cffi` won't be saved to the requests database
- `get_soup_cffi` will use cookies from the cookie files and the scraper session but any new cookies generated in the actual request will be discarded. Every new request will always use the same cookies
- Flaresolver will never be used if the request was made with `get_soup_cffi`
- We can't add trace logs to the requests made with …

feat: add custom `get_soup` method with `curl_cffi`

---

cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/scraper/__init__.py
cyberdrop_dl/scraper/crawler.py
cyberdrop_dl/scraper/crawlers/generic_crawler.py
cyberdrop_dl/scraper/scraper.py

The generic crawler will:
1. Make an initial request to get the headers of the URL.
2. If the content type is `html`, it will  get the soup and try to get a video file from it
3. If the content type is `text` or `json`, it will log the URL as unsupported
For any other content type, it will try to guess the extension of the file following this logic:
1. Get the extension from the URL name,
2. Get the extension from the URL name, but assuming the URL is from a forum
3. Guess the extension from the content type in the headers
1. If the crawler tried to get a video from the soup but there's no video, the URL will be logged as unsupported.
2. If they crawler can't guess the extension, it will log the URL as unsupported
3. If there's any request errors during the process, it will be logged as …

feat: replace `no_crawler` with a generic crawler to download from unsupported sites

---

cyberdrop_dl/scraper/crawlers/redgifs_crawler.py

API always returns the number of pages to get the first 1K posts only. We have to compute the actual number of pages
- Fixes #771

fix: download profiles with 1k+ posts (redgifs)

---

cyberdrop_dl/main.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/utils/constants.py
cyberdrop_dl/utils/logger.py

Replaces normal logging with a queued logging than delegates the writing of the log messages to a different thread.
This have the benefits of not blocking the loop with the file IO while still being able to use the main `log` function anywhere, without `await`.

perf: queue logging to prevent blocking the async loop 

---

cyberdrop_dl/config_definitions/custom/converters.py
cyberdrop_dl/config_definitions/custom/types.py
cyberdrop_dl/crawlers/crawler.py
cyberdrop_dl/crawlers/xenforo/xenforo.py
cyberdrop_dl/scraper/filters.py
cyberdrop_dl/scraper/scrape_mapper.py
cyberdrop_dl/utils/utilities.py

To be able to use it without the context of a crawler.

refactor: move `parse_url` to utils

---

cyberdrop_dl/clients/download_client.py

CDL will check the available free space periodically (every 512MB downloaded) instead of just checking when the file download starts
- Fixes #602

fix: concurrent free space check

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/crawlers/google_drive.py

Use server's `Last-Modified` value as the file date if we didn't get a date while scraping.
If `Last-Modified` is no available either, current datetime will be used

refactor: fallback to `Last-Modified` for file date

---

cyberdrop_dl/env.py
cyberdrop_dl/utils/args.py

User can still override it with `--no-portrait`

refactor: use portrait by default when running in termux

---

cyberdrop_dl/managers/live_manager.py

Disable textual UI for the next release.
UI freezes a lot if there are multiple input URLs that use the request cache. There's a blocking operation somewhere. I need to debug with a profile before releasing it.

refactor: disable textual UI

---

cyberdrop_dl/managers/client_manager.py

Whole error message is wrapped in `()` which can lead to situations like this:
```
Scrape Failed: https://redacted (DDoS-Guard - Config user_agent and flaresolverr user_agent do not match:
Cyberdrop-DL: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Flaresolverr: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
```
Quoting clarifies exact strings needed for config change

Clarify exact user agent on flaresolverr mismatch

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/config_definitions/global_settings.py
cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/managers/download_manager.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/managers/progress_manager.py
cyberdrop_dl/managers/storage_manager.py
cyberdrop_dl/ui/progress/file_progress.py
cyberdrop_dl/ui/textual.py
cyberdrop_dl/utils/args.py
cyberdrop_dl/utils/data_enums_classes/url_objects.py
poetry.lock
pyproject.toml

- The changes from #831 work but using a global lock blocks all downloads until the query for free space is ready, even if they will go to a different drive. 
- The internal chunk counter is reset after a single query so, if 2 downloads start at almost the same time, the original issue can still occur.
- We can take advantage of #814 by skipping querying free space for every file and just query the mount point they are using/will use and reuse the result of the query for every file that uses the same mount point.
This PR adds a helper class that runs a loop every 2 seconds to get the free space of every mount point in the system and keeps a dict with the values. This means we can check the available free space after every chunk written to disk by just querying the internal dict with the …

perf: use async loop to keep track of available space

---

cyberdrop_dl/crawlers/bunkrr.py

- Proper fix is #853 
- Reverts jbsparrow/CyberDropDownloader#851

Revert "fix: always deep scrape albums (bunkr)"

---

cyberdrop_dl/crawlers/__init__.py
cyberdrop_dl/crawlers/missav.py
cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/utils/ffmpeg.py
cyberdrop_dl/utils/utilities.py

This includes a major refactor of the core downloader to support HLS downloads. The implementation is specific to missav but can easily be generalized.
- Needs #764 
CDL downloads all the individual chunks of the stream, but keeping track of them in a single task (AKA a single file) and them mux them with `ffmpeg`. The drawback is that the user needs at least double the size of the file as free space. `ffmpeg` call is async
This PR also adds 4 new properties to the `MediaItem` class:
- `add_to_database`: `bool`
- `skip_hashing`: `bool`
- `quiet`: `bool` (do not log any errors and do not show anything in the UI)
- `reference`: `MediaItem` (a parent media item where all the file progress will be tracked)
I will refactor and split this into smaller PRs after the needed PRs are merged

feat: add missav support

---

CHANGELOG.md
cyberdrop_dl/ui/prompts/user_prompts.py

Only show the user browsers that are supported for import on their operating system.
Also change 'opera_gx' to display 'Opera GX'

[FEAT] Remove unsupported browsers from import menu

---

cyberdrop_dl/crawlers/__init__.py
cyberdrop_dl/crawlers/crawler.py
cyberdrop_dl/managers/client_manager.py
cyberdrop_dl/utils/data_enums_classes/url_objects.py
cyberdrop_dl/utils/utilities.py

The bug was introduced by 03407c3623c23b41a42bba85219d3e89090f7113 in here:
https://github.com/jbsparrow/CyberDropDownloader/blob/03407c3623c23b41a42bba85219d3e89090f7113/cyberdrop_dl/managers/client_manager.py#L203-L205
To check `DDos-Guard` errors, we need to create a soup, which means we need to await the response's `read()` method to get the content.
However, we do not keep a reference to that soup. If the check was successful (no `DDoS-Guard` detected), we create a new soup inside `ScrapeClient`,  which requires awaiting `read()` again.
Calling `read()` multiple times on a `CachedResponse` will silently return nothing after the first call. This is an upstream issue in `aiohttp_client_cache`. They fixed it a long time ago (2024-11-07) but the fix was not included until version v13.0, …

fix: downloader stalling and creating empty files

---

cyberdrop_dl/managers/manager.py
cyberdrop_dl/managers/mock_manager.py
cyberdrop_dl/scraper/scrape_mapper.py

- Generalize `MockManager` so we can use it for other simulated functions in future
- Simplify some functions calls
- Make sure only 1 instance of a `MockManager` is ever created

refactor: mock manager

---

cyberdrop_dl/crawlers/tiktok.py

- Fixes #766
May still be broken for images. The crawler does not define canonical URLs for images and I don't know enough about tiktok to define a format for them.

fix: use the canonical URL as the database entry (tiktok)

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/utils/data_enums_classes/url_objects.py

`task_id` has to always be an int at runtime after a8d7dc1a8625bbfb5d5b4bee0ef7636163a945bd
Also added a reference to a possible parent media_item to keep the same `task_id` accross multiple items (related to #857)

sync: merge fix `task_id` to release v6.9.0

---

cyberdrop_dl/main.py

Director has to import a lot of modules, which makes CDL take a few seconds to start up. If the user causes a keyboard interrupt, they will get a full traceback.
This change will suppress the traceback.

refactor: handle keyboard interrupts while still importing modules

---

cyberdrop_dl/crawlers/google_drive.py

- Fixes #931 
- Fixes Google Drive links being logged as `Unknown URL Path`, even if they were processed successfully.

fix: update download URL (GoogleDrive)

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/scraper/scrape_mapper.py

Do not create a new session for every requests

perf: use a single, global session for the entire run

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/utils/data_enums_classes/url_objects.py

Crawlers can pass an optinal fallback parameter to `handle_file`.  Fallback can be a list of URLs or a funtion that takes the response and the current retry as a parameter and returns a new URL.
If fallback if a function, the Funtion will be called indefinitely after every retry until it returns `None`

feat: add support for fallback URLs

---

cyberdrop_dl/downloader/downloader.py
poetry.lock
pyproject.toml

- Make updating files' dates non blocking.
- Remove `filedate` dependency. We only used it for this.
- Try to set "Creation time" in MacOS

perf: make setting file dates async

---

cyberdrop_dl/crawlers/kemono.py

Posts without files still have a `files` entry but it's an empty dict

fix: handle post without files (kemono)

---

cyberdrop_dl/crawlers/kemono.py

Making a request to the actual server that has the file removes the need of redirect by Cloudflare, which means no `DDoSGuard` checks.
@sublimal also mentioned it removed the likelihood of timeouts but i could not verify that.

refactor: try to use original server (kemono)

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/managers/client_manager.py
cyberdrop_dl/utils/utilities.py
poetry.lock
pyproject.toml

- Make a single, unique Curl session for the entire run
- Split methods that did multiple things or returned multiple types into individual methods. Each method now returns an specific type
- Crawlers can call private methods `_get_response_and_soup` or `_post_data` to get the actual response object, in case they need to do something with it.
- POST methods accept a `data` parameter or a `json` parameter
- All methods accept `headers` to include additional headers in the requests
- All methods accept arbitrary `**kwargs` to pass as parameters to the actual `session.request()` call
- Bump min `aiohttp_client_cache` version to v13.0.0 (See: https://github.com/jbsparrow/CyberDropDownloader/pull/879#issue-2987600035)
- Bump min certifi to current latest
This will (intentionally) break a lot …

refactor: generalize http request methods

---

cyberdrop_dl/crawlers/gofile.py

- Fix handling of nested items that we can not download
- Log frozen files as warnings
- Fix loose files folder creation
- Use a more restrictive fetch filter
- Skip files flagged by GoFile (dangerous)

fix: handle more gofile cases

---

cyberdrop_dl/ui/prompts/user_prompts.py
cyberdrop_dl/utils/cookie_management.py

Reduce the number of lines in users' configs when auto import is enabled by using names (`all`, `all_file_hosts`, and `all_forums`) to reference groups of domains.

Reduce the number of lines in auto import config

---

cyberdrop_dl/managers/manager.py
cyberdrop_dl/utils/utilities.py

Will show up as "Fedora Linux 42 (KDE)", "Windows 10 Home" or "macOS 14.0.5" in logs

refactor: show OS common name in logs

---

cyberdrop_dl/clients/scraper_client.py
cyberdrop_dl/crawlers/buzzheavier.py
cyberdrop_dl/crawlers/dropbox.py
cyberdrop_dl/crawlers/google_drive.py
cyberdrop_dl/utils/utilities.py

Regex sometimes fails. `aiohttp` uses actual logic to parse it

refactor: use aiohttp to get filename from headers

---

scripts/tools/filter_logs.py

It will filter all the `.log` files in the folder and create a single output file with just the errors

misc: allow folders as input (filter_logs)

---

cyberdrop_dl/constants.py

Add some sites that we do not support and will never support, but they seen to be common in profiles/forums. I see them frequently in user's logs.
Most users do not update their `--skip-hosts` list

perf: update blocked domains

---

cyberdrop_dl/crawlers/pornhub.py

match profile URLs by exact pattern, not just parts.
This means:
1. If the input  URL is the root of the profile, it will download videos, photos and gifs from that profile
2. If the URL is a subpath of the profile (videos, photos or gifs), it will only download videos, photos or gifs, respectively.
I also changed what's downloaded in each category:
- For gifs, it will only download gifs uploaded by the profile.
- For photos, it will only download photos uploaded by the profile.
- For videos, it will download all videos in the profile, which includes videos uploaded in the profile itself and videos that the model in the profile was tagged in. It will not include "similar videos", "related videos" or videos from other models
- Fixes #1098

refactor: use strict URL matching for all paths (pornhub)

---

cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/managers/manager.py
cyberdrop_dl/utils/ffmpeg.py

- Make `ffmpeg` no longer depend on the manager. Now is just a module with functions instead of a class
- Check `ffprobe` version and fallback to builtin binary if none is available

refactor: add `ffprobe` checks and fallback to builtin binary

---

CHANGELOG.md

it looks more like `2025-07-19` from where I am, but [pypi](https://pypi.org/project/cyberdrop-dl-patched/#history) says `Jul 18` so who am I to disagree. But it's very clearly not Jul 25 yet, unless you're on Mars or something.

fix obvious typo on `7.2.1` release date in changelog

---

cyberdrop_dl/clients/download_client.py
cyberdrop_dl/crawlers/crawler.py
cyberdrop_dl/data_structures/url_objects.py
cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/scraper/scrape_mapper.py

Leave the default constructor to build a completely new `media_item` from scratch.
- Related to #1148

refactor: add alternative constructor for media_item

---

cyberdrop_dl/crawlers/tiktok.py

Tiktok profile scraping returns exiting the loop when finding an image post, but I believe this is not intended, since we want to crawl all the videos/images of the profile, instead of leaving when we find one image post.
Fix exiting the loop when finding an image post and letting it crawl the entire user profile.

Fix tiktok profile scraping loop return

---

cyberdrop_dl/crawlers/google_drive.py
tests/crawlers/test_cases/google_drive.py

Google issues a warning when trying to download large files:
> `file_XYZ` is too large for Google to scan for viruses. Would you still like to download this file?
The original gdown code handles this by parsing the HTML response to extract a confirmation link and them make a new request.
Turns out we can bypass the warning by making a POST request instead of a GET request to the content URL.
For google docs links, the original code will make up to 3 additional requests to figure out the kind of file it was.
Now CDL will detect the type of document from the URL itself and validate with the id. 
- Add tests
- Add logic to validate file id
- Allow downloading google docs files with a custom format by using a `format` query param
- Process folder items in batches of 200 to prevent blocking …

perf: bypass google virus warning for large files (gDrive)

---

cyberdrop_dl/managers/db_manager.py
cyberdrop_dl/ui/program_ui.py
cyberdrop_dl/utils/database/tables/hash_table.py
cyberdrop_dl/utils/database/tables/history_table.py
cyberdrop_dl/utils/database/tables/temp_referer_table.py

- Remove redundant cursor references. Use the autocursor from the connection when possible.
- Give name to the queries and format them
- Group sequential startup queries as a single script to reduce thread switching
- Use `sqlite.Row` as row factory instead of the default `tuple`
- Related to #1086
I wanted to remove the `manager` dependency and move the entire module out of `utils` into the root folder but that will generate a huge diff and it will be difficult to identify what the actual changes are.
I will make a different PR for that
The `manager` is only used to get the value of `ignore_history` and the database path on instance creation.

refactor: cleanup database logic

---

cyberdrop_dl/crawlers/crawler.py
cyberdrop_dl/crawlers/gofile.py
cyberdrop_dl/crawlers/imgur.py
cyberdrop_dl/crawlers/mediafire.py
cyberdrop_dl/exceptions.py
cyberdrop_dl/managers/client_manager.py

Allow crawlers to define their own custom functions to check if a response was successful instead of hardcoding them in the client manager.

refactor: move custom response checks to crawlers

---

cyberdrop_dl/managers/client_manager.py

If we don't, the lock may get garbage collected by the weak ref dict before we use it, which gets us a `keyError` on the `async with` line .

fix: keep at least 1 reference for new file locks

---

cyberdrop_dl/config/config_model.py
cyberdrop_dl/crawlers/coomer.py
cyberdrop_dl/crawlers/kemono.py
docs/reference/configuration-options/settings/ignore_options.md
tests/crawlers/test_cases/kemono.py

The new `/posts`  endpoint they added a few weeks back does not return the text content of the posts. 
This PR adds a config option to make a new request per post to get it.
It also modifies the `ignore_coomer_ads` option to work on any of the kemono based crawlers

feat: add `ignore_coomer_post_content` option

---

cyberdrop_dl/utils/utilities.py

<h2>Purge empty files/dirs 30 times faster and without errors.</h2>
<p>Previously, the system to check for empty files and folders would have false positives if a folder contained a subfolder with files, but the parent folder did not have any files.</p>
<h3>Example</h3>
<pre>Folder1
└─ Folder2
├─ File1 (1 MB)
├─ File2 (9 MB)
└─ Folder3
└─ Folder4
└─ File3 (90 KB)</pre>
<p>With this folder structure, the old system would first try to delete <code>Folder1</code>, fail, then try to delete <code>Folder3</code>, and again, fail.</p>
<p>The new system is 10–30x faster depending on the amount of files being processed, and fixes the false-positive deletion attempts.</p>
<h3>Testing details</h3>
<p>Operating System: Windows 10<br>
Storage Device: 7200 RPM HDD<br>
<h4>Datasets</h4>
<table>
<thead> …

Perf & bugfix: Purge empty files/dirs 30 times faster and without errors

---

cyberdrop_dl/clients/download_client.py

Close download connections on exit. This was a regresion introduced by 1b53bdfada1ba11a200919119a652a72482338c3

fix: tcp leak

---

cyberdrop_dl/crawlers/crawler.py
cyberdrop_dl/data_structures/url_objects.py
cyberdrop_dl/database/__init__.py
cyberdrop_dl/database/tables/history.py
cyberdrop_dl/downloader/downloader.py
cyberdrop_dl/scraper/scrape_mapper.py
tests/test_database.py

We use the db path for every db lookup. We compute it every time before a lookup but this path will never change after the item is created.
Saving it as an attribute will allow us to simplify all db calls in the future since the only argument they will ever need is the `MediaItem` object.
- Related to #1086

refactor: save the database path as an attribute of `MediaItem`

---

cyberdrop_dl/clients/hash_client.py

The UI will go too fast while deleting cause it was designed to only show 1 file at a time but now we process them asynchronously

fix: incorrect hash being logged when deleting files

---

cyberdrop_dl/dependencies/__init__.py
cyberdrop_dl/dependencies/_browser_cookie3.py
cyberdrop_dl/director.py
cyberdrop_dl/ui/program_ui.py
cyberdrop_dl/utils/cookie_management.py

See: https://github.com/jbsparrow/CyberDropDownloader/pull/1322#issuecomment-3315356954
I also removed references to `wmi` and `shadowcopy`. They are really old, only needed on  windows, require admin rights and they are just a fallback anyway
I did not remove the actual dependencies from the toml file. I will do that in #1369

refactor: move to internal `browser_cookie3` again
